### ISSUE TITLE
this is undefined in browser.js 

### ISSUE THREAD

**Issue by THETCR** [Aymkdn/html-to-pdfmake#104]
From version 2.2.0 and upward, the library throws an exception when trying to bind "wndw" to this (which is undefined) in browser.js.
Tested in Chrome version 91.X

**Comment by Aymkdn** [comment]
Do you have some code, please? It may help me understand the issue.

**Comment by THETCR** [comment]
The problem is that the context of "this" you are binding to should already be available.
In a JavaScript function, the owner of the function is the default binding for this.

That means that if the caller, for instance, already has "this.wndw" defined you will overwrite it and if the call is being made from a context that doesn't have "this", for instance in strict mode, it will fail.

**Comment by Aymkdn** [comment]
Can you provide some code, please?

**Comment by Aymkdn** [comment]
Same question: can you provide your code, please? The way you call `html-to-pdfmake` and anything that could help me to find the issue?

**Comment by dancingCamel** [comment]
Angular Component:
`import { Component, ElementRef, ViewChild } from "@angular/core";
import htmlToPdfmake from "html-to-pdfmake";

import * as pdfMake from "pdfmake/build/pdfmake";

import pdfFonts from "../../pdfmake/vfs_fonts";

pdfMake.fonts = {
  Arial: {
    normal: "ARIAL.TTF",
    bold: "ARIALBD.TTF",
    italics: "ARIALI.TTF",
    bolditalics: "ARIALBI.TTF",
  },
  Roboto: {
    normal: "Roboto-Regular.ttf",
    bold: "Roboto-Medium.ttf",
    italics: "Roboto-Italic.ttf",
    bolditalics: "Roboto-MediumItalic.ttf",
  },
};

@Component({
  selector: "app-test-pdf",
  templateUrl: "./test-pdf.component.html",
  styleUrls: ["./test-pdf.component.scss"],
})
export class TestPdfComponent {
  @ViewChild("reportPreviewHtmlWrapper") reportPreviewHtmlWrapper: ElementRef;

  constructor() {
    // we need to attach the pdfMake virtual file system otherwise fonts can't be accessed
    (<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;
  }

  generatePdf(): void {
    const pdf = this.preparePdf(
      this.reportPreviewHtmlWrapper.nativeElement.innerHTML
    );

    pdf.download(`test pdf`);
    pdf.open({}, window);
  }

  preparePdf(html: string): any {
    const reportPdfMakeStack = htmlToPdfmake(html, {
      tableAutoSize: true,
    });

    const toc = {
      toc: {
        title: {
          text: "Contents",
          style: "section-title",
          pageBreak: "before",
        },
        textStyle: {
          color: "#522583",
          bold: true,
        },
        numberStyle: {
          color: "#522583",
          bold: true,
        },
      },
      margin: [100, 10],
    };

    // Add the toc to the document stack in the desired place
    // Currently after the first node
    reportPdfMakeStack.splice(1, 0, toc);

    const documentDefinition = {
      pageMargins: [40, 60],
      watermark: {
        text: "test watermark",
        color: "blue",
        opacity: 0.1,
        bold: true,
        italics: false,
      },
      content: [reportPdfMakeStack],
      styles: {
        "doc-title": {
          color: "#522583",
          bold: true,
          fontSize: 18,
          decoration: "underline",
          markerColor: "",
          alignment: "center",
        },
        "section-title": {
          color: "#522583",
          bold: true,
          fontSize: 16,
        },
      },
      defaultStyle: {
        font: "Arial",
      },
      pageBreakBefore(currentNode) {
        // Add the function check so don't get error on toc
        return (
          currentNode.style &&
          typeof currentNode.style.indexOf === "function" &&
          currentNode.style.indexOf("pdf-pagebreak-before") > -1
        );
      },

      footer(currentPage, pageCount) {
        return {
          text: currentPage.toString(),
          alignment: "right",
          margin: [0, 0, 40, 0],
        };
      },
    };

    // Make the pdf
    const pdf = pdfMake.createPdf(documentDefinition);

    return pdf;
  }
}`

HTML being wrapped: `<div class="" #reportPreviewHtmlWrapper>
  <div class="doc-title">Title Page</div>

  <div data-pdfmake='{"margin":[0,0,0,0]}'>
    <div class="section-title pdf-pagebreak-before"
      data-pdfmake='{"tocItem":true,"tocMargin":[0,30,0,0], "pageOrientation":"portrait"}'>
      Paragraphs
    </div>
    <div style="
              color: blueviolet;
              font-size: 18px;
              font-weight: bold;
              margin-left: 3rem;
            ">
      pass css syles inline to affect text
    </div>
  </div>
  <div>

    <div class="section-title" [class.pdf-pagebreak-before]="true"
      data-pdfmake='{"tocItem":true,"tocMargin":[0,30,0,0], "pageOrientation":"portrait"}'>
      Lists
    </div>

  </div>
</div><button mat-raised-button color="accent" (click)="generatePdf()">
      Generate Pdf
    </button>`

**Comment by Aymkdn** [comment]
Thanks for sharing. I have to leave now, but I'll work on it tomorrow morning (France timezone).

**Comment by THETCR** [comment]
@Aymkdn I tried to explain the issue to you, but maybe I wasn't clear enough.

html-to-pdfmake exports a function, it doesn't have it's own "this".
The "this" you are trying to use is from your end users. Which you should not do.

They might call the exported function in a context that doesn't have "this" and since you are also trying to bind properties to it on the root level you might overwrite properties that your end users already have defined.

**Comment by Aymkdn** [comment]
I've just released v2.2.4 – can you try this version?

Please, let me know if it looks good now.

**Comment by dancingCamel** [comment]
Hi,

Seems to be working now. Thanks :)

**Comment by Aymkdn** [comment]
Great! Thanks! :)
