### ISSUE TITLE
Link is not clickable in some circonstances

### ISSUE THREAD

**Issue by Prakash-karena** [Aymkdn/html-to-pdfmake#107]
**Description**

Link not clickable if first added any style on text(bold/underline) and after that added link.
it is causing problem to show that pdf. i have logged bug there as well but as discussed with pdfmake team that link should come  in text but here in this case not comming https://github.com/bpampuch/pdfmake/issues/2276#issue-927253522

Please check this comment https://github.com/bpampuch/pdfmake/issues/2276#issuecomment-866696750

**Steps to reproduce**
  I have used html-to-pdfmake to convert html to pdf and used that value inside pdfmake and after that once pdf generated i have used that pdf here. into that pdf link is not clickable.

**Expected behavior**
  link should be clickable even if strong added first and after that link is added

**Additional information**

![Screenshot from 2021-06-22 19-09-18](https://user-images.githubusercontent.com/63772512/122934701-63042e80-d38d-11eb-8b3d-9bf0bdfd52d5.png)

Here on above supermart first added bold after that added link so that is not clickable and  on below supermart first added link and after that added bold so that is clickable.

**Environment** : any

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: any 
 - React-PDF version [ 4.2.0]:
 - React version [16.13.1]:

**Comment by Aymkdn** [comment]
I went to [my playground](https://aymkdn.github.io/html-to-pdfmake/index.html), then I entered the code `<a href='https://www.google.com'><strong>Google</strong></a>`, then I generated the PDF: the link is clickable in both the browser and if I download the file…

Please, provide your HTML code if it's different from the above.

**Comment by Prakash-karena** [comment]
`<p>This is example of link added first and after that added bold :- <strong><a href="https://www.google.com/">Google</a></strong>&nbsp;</p>↵↵<p>This is example of bold added first and after that added link :- <a href="https://www.google.com/"><strong>Google</strong></a>&nbsp;</p>↵↵<p>&nbsp;</p>`

here on above a is inside strong so it is clickable but below a is parent element so at that time it is not working.

**Comment by Aymkdn** [comment]
It's tricky. I'll try to find a solution later today.

**Comment by Prakash-karena** [comment]
Ok @Aymkdn

**Comment by Aymkdn** [comment]
I've just published v2.2.5 that should fix this issue.

**Comment by Prakash-karena** [comment]
Thank you so much @Aymkdn  link is now clickable.
