### ISSUE TITLE
Support External Image via URL

### ISSUE THREAD

**Issue by seanwu1105** [Aymkdn/html-to-pdfmake#109]
According to [the docs](https://pdfmake.github.io/docs/0.1/document-definition-object/images/), after pdfmake 0.1.67, external image with http or https URL is supported.

I think it would be possible to extract all `src` from `<img />` elements to generate the `images` field in `docDefinition`.

``` javascript
const docDefinition = {
  content: [
    {
      // if you reuse the same image in multiple nodes,
      // you should put it to to images dictionary and reference it by name
      image: 'mySuperImage'
    },
    {
      // in browser is supported loading images via url from reference by name in images
      image: 'snow'
    },
  ],

  images: {
    mySuperImage: 'data:image/jpeg;base64,...content...',

    // in browser is supported loading images via url (https or http protocol) (minimal version: 0.1.67)
    snow: 'https://picsum.photos/seed/picsum/200/300'
  }
```

**Comment by Aymkdn** [comment]
OK, I'll update the documentation to let people know. Thanks.

**Comment by seanwu1105** [comment]
@Aymkdn Is it possible to add the automatic extraction functionality to this repo? Thus, we do not have to take care about the image ourselves on using `html-to-pdfmake`.

I think it could be accomplished by:

1. Extracting all `src` in `<img>` elements.
2. Replacing the original `src` value with auto-incremental id.
3. Generating the `images` property with the extracted values and the auto-incremental id.

**Comment by Aymkdn** [comment]
I've just created v2.3.0 with the new option [`imagesByReference`](https://github.com/Aymkdn/html-to-pdfmake#imagesbyreference)

I partially tried it, so feel free to give it a try and let me know if it works correctly.

**Comment by seanwu1105** [comment]
@Aymkdn It works perfectly! Thanks for the swift response for this new feature.

**Comment by ankesh-paramanik** [comment]
> I've just created v2.3.0 with the new option [`imagesByReference`](https://github.com/Aymkdn/html-to-pdfmake#imagesbyreference)
> 
> I partially tried it, so feel free to give it a try and let me know if it works correctly.

Hi @Aymkdn 
Is there a way to pass custom headers as well?
Since there is an option to send custom headers in the [pdfmake](https://pdfmake.github.io/docs/0.1/document-definition-object/images/).
