### ISSUE TITLE
Inline styles lost upon conversion

### ISSUE THREAD

**Issue by AndrewMcEwenSW** [Aymkdn/html-to-pdfmake#111]
I am trying to convert something similar to the following html:

`<p style="padding-left: 100pt;">Hello</p>`
`<p style="padding-left: 50pt;">World</p>`

Unfortunately, the inline styles are not preserved upon conversion.

This is happening in the playground as well. See screenshot.

How can I maintain these inline styles when I convert the html?

![image](https://user-images.githubusercontent.com/80841246/126218589-2e6b16f9-5839-48da-a5a0-a53fe96b2e27.png)

**Comment by Aymkdn** [comment]
`padding` is not a supported property by PDFMake (that I'm aware of), so you'll have to use `margin` instead of `padding`:
```html
<p style="margin-left: 100pt;">Hello</p>
<p style="margin-left: 50pt;">World</p>
```

Also I found a bug when using `margin` in this configuration and I've just fixed it in v2.3.2, so make sure to upgrade first.
