### ISSUE TITLE
Support for flexbox

### ISSUE THREAD

**Issue by polymer-coder** [Aymkdn/html-to-pdfmake#113]
Hi!

Amazing work on this package! Does it support flexbox?

**Comment by Aymkdn** [comment]
No it doesn't. Only basic HTML with very few CSS

**Comment by polymer-coder** [comment]
@Aymkdn thank you! I understand. Is it possible to add a  list of supported css attributes?

**Comment by Aymkdn** [comment]
I'll update the documentation in the next release.

In the meantime:
  - background-color
  - border
  - color
  - font-family
  - font-style (with `italic`)
  - font-weight (with `bold`)
  - height
  - margin
  - text-align
  - text-decoration
  - text-indent
  - white-space (with `break-spaces` and `pre*`)
  - width
