### ISSUE TITLE
font-size and line-height don't seem to work together but work separately

### ISSUE THREAD

**Issue by techquestions** [Aymkdn/html-to-pdfmake#114]
First of all, thank you for your work.

I have tried the following code snippet:

```
 <div style="font-size:2.5rem;line-height: 3rem;">
  font-size and line-height used together
</div>
<div style="font-size:2.5rem;">
  font-size only
</div>
<div style="line-height: 3rem;">
  line-height only
</div>
```

It looks like `font-size` and `line-height` don't seem to work when used together - nothing is rendered in the generated PDF. Can you please take a look at that?

**Comment by Aymkdn** [comment]
It's a PDFMake thing, and it's not related to my library. If you use the below code in the [PDFMake Playground](http://pdfmake.org/playground.html) you'll find the same result:
```js
var dd = {
  "content": [
    {
      "text": "font-size and line-height used together",
      "fontSize": 30,
      "lineHeight": 36
    }
  ]
}
```

My guess is that PDFMake does an incorrect operation with the `font-size` and the `line-height`, causing a very large line height. If you change the `line-height` from 36 to 6, you'll see the text appears correctly.

In the PDFMake source code, there is: https://github.com/bpampuch/pdfmake/blob/master/src/TextInlines.js#L137
And this `item.font.lineHeight` seems to be related to the below code found [in the build](https://raw.githubusercontent.com/bpampuch/pdfmake/7bedee9292c327d612fadf90171b33e8c8f8685d/build/pdfmake.js):
```js
{
    key: "lineHeight",
    value: function lineHeight(size, includeGap) {
      if (includeGap == null) {
        includeGap = false;
      }

      var gap = includeGap ? this.lineGap : 0;
      return (this.ascender + gap - this.descender) / 1000 * size;
    }
  }
```

That brings us to this 4-years-old issue: https://github.com/bpampuch/pdfmake/issues/845

Long answer short: _it's a PDFMake issue and I'm not sure how I can mitigate it_

**Comment by techquestions** [comment]
Thank you for a prompt response. In that case we will have to wait for the changes in `pdfmake`.
