### ISSUE TITLE
Take into account margin: auto

### ISSUE THREAD

**Issue by SamuelHassine** [Aymkdn/html-to-pdfmake#119]
Hello,

Thanks for the great work here! Currently, when using `style="margin: 0 auto;` on an element, the element is not centered in the PDF page.

I propose to take into account this CSS style for centering element.

Kind regards,
Samuel

**Comment by Aymkdn** [comment]
It's not possible to handle all the little things related to the CSS styles. Dealing with such a rule doesn't seem reasonable and nearly impossible to manage correctly. 

Sorry.

**Comment by Aymkdn** [comment]
If you know a trick in PDFMake that would make this rule working with all possible cases, then of course I open to a documented solution!
