### ISSUE TITLE
It shows nothing when using UL

### ISSUE THREAD

**Issue by huonsokly** [Aymkdn/html-to-pdfmake#121]
I've tried to use ul in text of pdfMake with html-to-pdfmake but it shows nothing.
strong, div, ... working normal.

`{text: htmlToPdfmake('<ul><li>Create, Edit and Delete User</li><li>Assign Role<br></li></ul>')}`

Please Help!

**Comment by Aymkdn** [comment]
You should not use it this way. Generate the PDFMake code and then use it directly in PDFMake. Why do you pass it to a `{text} `?! 
Did you even try to see the output of the `htmlToPdfmake` call?

**Comment by huonsokly** [comment]
Thank you for your reply.
`let html = htmlToPdfmake('<ul><li>Create, Edit and Delete User</li><li>Assign Role<br></li></ul>');`

`
let docDefinition = {
                    content: html
                };`

`pdfMake.createPdf(docDefinition).open();`

It worked, but I want to use it inside of content.
