### ISSUE TITLE
Strikethrough position with superscript and subscript

### ISSUE THREAD

**Issue by golcsa-renato** [Aymkdn/html-to-pdfmake#126]
I tried to add `strikethrough` to `superscript` and `subscript` but the position of the line isn't where it should be. 

```
var dd = {
    content: [{
        text: [
            'Some text with',
            {
                text: 'superscript ',
                sup: {},
                decoration: 'lineThrough'
            },
            'and with',
            {
                text: 'subscript',
                sub: {},
                decoration: 'lineThrough'
            },
        ]
    }, ],
}
```
![html-to-pdfmake-issue-image](https://user-images.githubusercontent.com/31313767/142042415-7bc352a3-dfc0-4925-a598-31c9e1841fff.png)

The snippet is from the official [Playground](http://pdfmake.org/playground.html)

**Comment by Aymkdn** [comment]
Can you provide three things?

1. The HTML code you're trying to convert to PDFMake
2. The html-to-pdfmake result that you get from the HTML
3. The result code that you expected to get, and that works in the [PDFMake Playground](http://pdfmake.org/playground.html)

**Comment by golcsa-renato** [comment]
> Can you provide three things?
> 
> 1. The HTML code you're trying to convert to PDFMake
> 2. The html-to-pdfmake result that you get from the HTML
> 3. _The result code that you expected to get, and that works in the [PDFMake Playground]_(http://pdfmake.org/playground.html)

My main problem is that I can't create the expected outcome I want (superscript or subscript with strikethrough) in the playground. As shown previously in the image the lines are not in place.

**Comment by Aymkdn** [comment]
Then you need to post on PDFMake repository and not on this one....
