### ISSUE TITLE
Cannot read property 'text' of undefined Error when parsing empty <a href="XYZ"></a> tag

### ISSUE THREAD

**Issue by hschmidtchen** [Aymkdn/html-to-pdfmake#128]
Hello @Aymkdn,

thank you for this awesome library!

I just encountered an error where it seems like it currently has a problem dealing with link tags that do have an href attribute but no enclosed text.

The error does not occur if there is no href attribute or any characters enclosed by the <a></a> tags

Here is a minimal example to reproduce it in the online demo:

This doesnt work:

`<a href="https://www.github.io"></a>
`

![image](https://user-images.githubusercontent.com/7461847/144291169-330b93e4-ac89-4082-a700-a90ff3fc181f.png)

But this works:

`<a href="https://www.github.io"> </a>
`

I hope that this helps you to improve the project! :)

**Comment by hschmidtchen** [comment]
You are right. It doesnt make sense from a use case perspective if someone creates this on purpose.

Unfortunately, in my case the HTML is usually user generated content (might be copy&paste from somewhere else) and there was a case where that content contained such an empty tag. Rendering that content works totally fine.

Sorry that I cant give you a better answer than that. 

Do you think it makes sense to handle this edge case?

**Comment by Aymkdn** [comment]
I'll check tomorrow if it's not too much trouble and I'll let you know.

**Comment by Aymkdn** [comment]
Added support in the new release v2.3.7
