### ISSUE TITLE
Issue with bold and br element

### ISSUE THREAD

**Issue by 1Apar** [Aymkdn/html-to-pdfmake#13]
I have the following input html string:

`<p><b>Text 1 Bold<br> continue with bold in new line 1<br>continue with bold in new line 2</b><br> simple text <br> simple text <br><b>another bold line</b><br></p>` 

The output I get is as follows ( can be tested in pdfmake playground) : 
<pre>
var dd = {
	content: [
        {
          "text": [
            {
              "stack": [
                {
                  "text": "Text 1 Bold",
                  "bold": true
                },
                "\n",
                {
                  "text": " continue with bold in new line 1",
                  "bold": true
                },
                "\n",
                {
                  "text": "continue with bold in new line 2",
                  "bold": true
                }
              ],
              "style": [
                "html-b"
              ]
            },
            "\n",
            {
              "text": " simple text "
            },
            "\n",
            {
              "text": " simple text "
            },
            "\n",
            {
              "text": "another bold line",
              "bold": true,
              "style": [
                "html-b"
              ]
            },
            "\n"
          ],
          "margin": [
            0,
            5,
            0,
            10
          ],
          "style": [
            "html-p"
          ]
        }
	]
} 
</pre>
which results in some text truncation : 

![result](https://user-images.githubusercontent.com/49903337/64413737-b7e09300-d09a-11e9-9d5b-63f9d575f074.png)

The desired output : 
![expected](https://user-images.githubusercontent.com/49903337/64413760-c464eb80-d09a-11e9-9f6a-e8616259d3d1.png)

**Comment by Aymkdn** [comment]
You better use CSS instead of incorrect HTML. `<b>` is inline and use it with a `<br>` doesn't make sense. So it's a no fix from my point of view. Sorry...
