### ISSUE TITLE
Wrong unit conversion for table dimensions (v2.3.8)

### ISSUE THREAD

**Issue by ivesdebruycker** [Aymkdn/html-to-pdfmake#130]
Commit 4b33b05 changed table widths transformation when using tableAutoSize.
`<td style="width:40%;">` is transformed into `widths: [ 0.4 ]`, it should be `widths: [ '40%' ]` as it was before v2.3.8.

**Comment by Aymkdn** [comment]
Thanks for submitting. I'm on vacation aboard until Feb 3rd. I'll review when I'm back.

**Comment by Aymkdn** [comment]
I published v2.3.9 that should fix the issue.
