### ISSUE TITLE
Alignment of Images

### ISSUE THREAD

**Issue by hernantk** [Aymkdn/html-to-pdfmake#132]
Hello, a i'm trying to align a image using margin-left: auto; margin-right: auto; , but with doesn't work, the pdf does not generate, i try using text-align:center, in the HTML does not centralize, but the in the PDF works.

![Not Generate](https://user-images.githubusercontent.com/51250549/152588325-d7369fa5-419a-409c-8b93-11debd84aa49.png)

**Comment by Aymkdn** [comment]
You have to check which properties are supported by `pdfmake` and how to do it with it. 

My library only translates the html code to pdfmake, but there are multiple limitations (like using CSS to style a page).

So, once you found what is supported by pdfmake and if you think my library doesn't translate something correctly, then you can get back to me.
