### ISSUE TITLE
Feature request: Could not parse color "rgb(100.000000%, 100.000000%, 100.000000%)"

### ISSUE THREAD

**Issue by jamesxwang** [Aymkdn/html-to-pdfmake#134]
Hi @Aymkdn,

Thanks for the life-saver library!

As [`color`](https://github.com/Aymkdn/html-to-pdfmake#css-properties-supported) attribute is supported for css, is there any possible to add color parsers for [rgb](https://www.w3schools.com/colors/colors_rgb.asp) and [hsl](https://www.w3schools.com/colors/colors_hsl.asp)?

**Comment by Aymkdn** [comment]
`rgb` is supported already, but not with percentages. For example, `rgb(255, 255, 255)`. I didn't know we could even have a percentage for `rgb`…

I'll see to add `hsl` support. I'm not sure I'll have the time today, so maybe tomorrow.

**Comment by Aymkdn** [comment]
It's now available in v2.3.10
