### ISSUE TITLE
Add strikethrough support and problem with margin in <li>

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/html-to-pdfmake#14]
`<p>Here I am.</p><p><br></p><p>I'm another sentence two lines down. <s>Some strike through.</s></p><p><br></p><ul><li>list item 1</li><li class="ql-indent-1">list item 1.2</li><li>list item 2</li></ul><p><br></p><p><br></p>`

this produces 
![Screen Shot 2019-09-17 at 2 18 23 PM](https://user-images.githubusercontent.com/30310399/65080532-5e0f8100-d956-11e9-83ee-0eb485d37a0b.png)

Here is the same output in our UI's text field which uses the vue2-editor package

![Screen Shot 2019-09-17 at 2 19 50 PM](https://user-images.githubusercontent.com/30310399/65080522-59e36380-d956-11e9-83e6-1d6b1798d8db.png)

There are 3 problems:
No strike through
2nd sentence is on line 2 instead of line 3.
Lists aren't displayed at all.

Thank you.

_Originally posted by @SunnysideAaron in https://github.com/Aymkdn/html-to-pdfmake/issues/8#issuecomment-532407804_

**Comment by Aymkdn** [comment]
Several things here:
1. `<s>`, as shown in the documentation, is not a supported tag; I've just added support to `<s>` in the new release;
2. `"2nd sentence is on line 2 instead of line 3"`: no, it's not.... if you look at the [playground](https://aymkdn.github.io/html-to-pdfmake/index.html), you'll see it appears on the 3rd line, so my guess is that something is wrong with your code;
3. `"Lists aren't displayed at all"`: lists are correctly displayed in the  [playground](https://aymkdn.github.io/html-to-pdfmake/index.html), so I think something is wrong with your code.

That says, it wasn't possible to change the default margin left for `list item 1.2` because I've just discovered that the default style will be stronger than a style class... In the new release, I've introduced an option parameter to the function in order to overwrite the default styles.

For your specific example, the full code will look like that:
```javascript
// here there is your HTML code
var html = htmlToPdfMake(`<p>Here I am.</p>
<p><br></p>
<p>I'm another sentence two lines down. <s>Some strike through.</s></p>
<p><br></p>
<ul>
    <li>list item 1</li>
    <li class="ql-indent-1">list item 1.2</li>
     <li>list item 2</li>
</ul>
<p><br></p>
<p><br></p>`, {
  defaultStyles:{
    li:'' // remove all the default styles for LI (including the margin)
  }
});

var docDefinition = {
  content: [
    html
  ],
  // define some style classes to provide the margins for your LI
  styles:{
    'html-li':{ // here is the default margin for all LI
      marginLeft:5
    },
    'ql-indent-1':{ // here is the margin to use when we have 'ql-indent-1'
      marginLeft: 15
    }
  }
};

// and finally you can use pdfMake to create the PDF
pdfMake.createPdf(docDefinition);
```

The above code will return the below PDFMake code that you can test in the [PDFMake Playground](http://pdfmake.org/playground.html):
```javascript
var dd = {
  content: [{
      text: 'Here I am.',
      style: ['html-p'],
      margin: [0, 5, 0, 10]
    },
    '\n',
    {
      text: [{
          text: 'I\'m another sentence two lines down. ',
          style: ['html-p']
        },
        {
          text: 'Some strike through.',
          style: ['html-s'],
          decoration: 'lineThrough'
        }
      ],
      margin: [0, 5, 0, 10],
      style: ['html-p']
    },
    '\n',
    {
      ul: [{
          text: 'list item 1',
          style: ['html-li']
        },
        {
          text: 'list item 1.2',
          style: ['ql-indent-1', 'html-li']
        },
        {
          text: 'list item 2',
          style: ['html-li']
        }
      ],
      style: ['html-ul'],
      marginBottom: 5
    },
    '\n',
    '\n'
  ],
  styles: {
    'html-li':{ // here is the default margin for all LI
      marginLeft:5
    },
    'ql-indent-1':{ // here is the margin to use when we have 'ql-indent-1'
      marginLeft: 15
    }
  }
}
```

Here how it looks like:
![Capture](https://user-images.githubusercontent.com/946315/65131665-f0b82a80-d9ff-11e9-9ad3-a6ff79a61bd8.JPG)

Please, not the new version is `1.1.0`, so a simple `npm update` won't update it.
I have updated the documentation too.

**Comment by SunnysideAaron** [comment]
Thank you for the thorough response. I'll look into this on my end today

**Comment by SunnysideAaron** [comment]
Thank you again. It turns out that it was with our code. We had wrapped our text in another text array, which was fine for text elements but not ul elements. I've started work on a solution for that. but now I'm getting another related issue I'll open a different ticket for.
