### ISSUE TITLE
TypeScript definitions update

### ISSUE THREAD

**Issue by whawker** [Aymkdn/html-to-pdfmake#140]
Hi @Aymkdn,

I wanted to update the [DefinitelyTyped definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-to-pdfmake/index.d.ts) for this project, and I wanted to sense check the changes with you.

Essentially the definitions above do not know about the `imagesByReference` option, and how that changes the response.

Additionally the definitions above do not include the `customTag` option either - I've tried my best to figure out the param types, and result of this function, by reading through the code but I suspect they're not bullet proof.

For instance it looks like `nodeName` and `id` are non-standard properties of a content item? So I've added the "Decorated" types below.

### The definitions

```ts
import type {
  Content,
  ContentStack,
  ContentText,
  StyleDictionary,
} from 'pdfmake/interfaces';

interface DecoratedContentStack extends ContentStack {
  nodeName: string;
  id?: string;
}

interface DecoratedContentText extends ContentText {
  nodeName: string;
  id?: string;
}

interface CustomTagParams {
  ret: DecoratedContentStack | DecoratedContentText;
  element: HTMLElement;
  parents: HTMLElement[];
}

interface Options {
  /**
   * You can overwrite the default styles using defaultStyles.
   * Please, note that the above default styles are stronger than the ones defined in the style classes.
   */
  defaultStyles: StyleDictionary;
  /**
   * You can overwrite the default sizes for the old HTML4 tag <font> by using fontSizes. It must be an array with 7 values
   */
  fontSizes: [number, number, number, number, number, number, number];
  /**
   * By passing replaceText as a function with two parameters (text and nodes) you can modify the text of all the nodes in your HTML document.
   */
  replaceText: (text: string, nodes: HTMLElement[]) => string;
  /**
   * By passing tableAutoSize with true, then the program will try to define widths and heights for the tables, based on CSS properties width and height that have been provided to TH or TD.
   */
  tableAutoSize: boolean;
  /**
   * If you use Node, then you'll have to pass the window object
   */
  window: import('jsdom').DOMWindow;
  /**
   * If your HTML code doesn't use regular HTML tags, then you can use customTag to define your own result.
   */
  customTag: (
    params: CustomTagParams
  ) => DecoratedContentStack | DecoratedContentText | Content;
}

interface ImageOptions {
  /**
   * If you're using a web browser with images, then you can set this option to automatically load your images in your PDF using the {images} option of PDFMake.
   */
  imagesByReference: true;
}

declare function htmlToPdfmake(html: string): Content;
declare function htmlToPdfmake(
  html: string,
  options: Partial<Options>
): Content;
declare function htmlToPdfmake(
  html: string,
  options: ImageOptions & Partial<Options>
): {content: Content; images: Record<string, string | null>};

export = htmlToPdfmake;
```

**Comment by Aymkdn** [comment]
I don't use TypeScript at all, so it's quite confusing for me. Then you can define whatever you want, as I don't really care 😅

If you have a specific question, I can try to answer it, but you'll have to be very precise.

**Comment by whawker** [comment]
No worries, I only really started using typescript a year or so ago myself (I would recommend it, for what it's worth)

Re specific questions.
1. Regarding `customTag`, what is the `ret` parameter? It looks as if it could be something placed into the `content`  array for pdfMake?
2. If 1 is correct, could `nodeName` and `id` be provided separately to `customTag` (see comment above) this would make the types easier

**Comment by Aymkdn** [comment]
> 1. Regarding `customTag`, what is the `ret` parameter? It looks as if it could be something placed into the `content`  array for pdfMake?

The `ret` is the JSON object that represents the HTML tag that is passed (`parseElement` is a recursive function). So you can imagine `customTag` as the `parseElement` function, but defined by the user. It will return a JSON object (that will be, at the end, a part of the big JSON object used by PDFMake).

> 2. If 1 is correct, could `nodeName` and `id` be provided separately to `customTag` (see comment above) this would make the types easier

The [parameters for `customTag`](https://github.com/Aymkdn/html-to-pdfmake/blob/f6a649c30f5b691404fc839d96edddffe6a37d72/index.js#L479) are: `{element, parents, ret}`

I'm not sure why you're talking about `nodeName` and `id`? I don't use them in [the example](https://github.com/Aymkdn/html-to-pdfmake#customtag)…

**Comment by whawker** [comment]
> I'm sorry but at this point I don't see why I should change my code to accomodate a Type definition…

I wasn't trying to start an argument or anything. I was asking for clarification to validate my understanding of the `customTags` function, but clearly I don't understand everything going on here. 

I didn't want to put wrong definitions out there as that would be more damaging than no definitions at all.

> I don't understand what is the link between the input parameters and the output of the function?!

The link is that we have ret as a parameter, which is later returned

```js
  customTag:function(params) {
    var ret = params.ret; // <- get ret here
    var element = params.element;
    var parents = params.parents;
    switch(ret.nodeName) {
      // Some cases
    }

    return ret; // <- output same var here
  }
```

But as I say, it looks like I misunderstood the function.

All the best
