### ISSUE TITLE
Page indexing

### ISSUE THREAD

**Issue by rravindranaik111** [Aymkdn/html-to-pdfmake#144]
Can we create a page indexing and track in which page which content has contain a data.

**Comment by Aymkdn** [comment]
Please, provide the HTML code sample, as well as the expected result in PDFMake language.

**Comment by rravindranaik111** [comment]
Thanks for the reply. Suppose for example I want output as attached image
![images](https://user-images.githubusercontent.com/25271489/175008047-49e114ec-58c7-458f-9111-de2556d5a0cb.jpeg)

**Comment by Aymkdn** [comment]
It exists in PDFMake: https://pdfmake.github.io/docs/0.1/document-definition-object/toc/

However I'm not sure how the HTML part should look like... Maybe by using a personal HTML attribute (like `data-toc="Chapter 1: The Beginning"`), or by using an automatic system based on `H1`, `H2`, …

So in theory, it would be possible, however:
- I'm not sure to understand the need for this kind of table of content when we transform an HTML code to PDF ? Do you have an example?
- It will require some development effort, so it will take several weeks before being available

**Comment by rravindranaik111** [comment]
Ok will try that solutions

Thanks for your quick and accurate reply
