### ISSUE TITLE
Parsing style values that start with . fail like `style="margin-bottom:.0001pt"`

### ISSUE THREAD

**Issue by fonss95** [Aymkdn/html-to-pdfmake#152]
When passing an html string to the `htmlToPdfmake` function that contains style tags with values that start without a digit but rather with a . instead of converting it to a valid number it is leaving them as a string and therefor the makePdf is throwing an error since it is expecting  a valid number. 

html input string: 
`<span style="margin-bottom: .0001pt"></span>`

pdfMake object expected to be returned:
` { text: [ { text: '', nodeName: 'SPAN' } ], nodeName: 'P', margin: [ 0, 0, 0, 0.0001 ], style: [ 'html-p', 'html-div' ]  }`

instead it is currently returning:
` { text: [ { text: '', nodeName: 'SPAN' } ], nodeName: 'P', margin: [ 0, 0, 0, '.0001pt' ], style: [ 'html-p', 'html-div' ]  }`

**Comment by Aymkdn** [comment]
Thanks for the submission. I've just released a new version with the fix.
