### ISSUE TITLE
Image Size change

### ISSUE THREAD

**Issue by KorthaseC** [Aymkdn/html-to-pdfmake#154]
Hi, 
I is there a way to change the size of the image wenn its inside a rich text field editor? I would like to convert the value of a rich text field but it seems thats its not possoble to change the files size with `style:{'hmtl-img':maxWitdh: '1000px'}`

**Comment by Aymkdn** [comment]
Please, provide the HTML code that you try to convert to PDFMake.

**Comment by KorthaseC** [comment]
I uploaded the value of the rich text field here:
https://controlc.com/270f6a7b

**Comment by Aymkdn** [comment]
For some reasons, the `width` and `maxWidth` in the PDFMake `styles` don't seem to work for images. You may want to open an [issue to PDFMake](https://github.com/bpampuch/pdfmake/issues) to report it:
![image](https://user-images.githubusercontent.com/946315/195871343-f2a5c4f9-dd66-442b-bbd9-5132515ec98b.png)


In the meantime, you'll have to modify the HTML code you send to my library to include the `max-width` on the `<img>` tag.

Sorry, but as it's a bug in PDFMake, I cannot do anything more for you.

**Comment by KorthaseC** [comment]
okay thank you
