### ISSUE TITLE
Issue of convert html to HtmlToPdf

### ISSUE THREAD

**Issue by AnassLAMAALAM** [Aymkdn/html-to-pdfmake#155]
I used red color inside a italic text in angular-editor coponent , the issue is the pdf take just italic style without color.

**Comment by Aymkdn** [comment]
Please, provide the HTML code you try to convert.

**Comment by AnassLAMAALAM** [comment]
<i>
    <font color="#ff0000" size="1">
        <span>Qu'est-ce que le Lorem Ipsum?
</span>
    </font>
</i>

**Comment by Aymkdn** [comment]
Can you simply your HTML code? Instead of using all these tags, you could do the below that will then work:
> &lt;i style="color:#ff0000">Qu'est-ce que le Lorem Ipsum?&lt;/i>

**Comment by AnassLAMAALAM** [comment]
I can't bcause the code generete from  [https://github.com/kolkov/angular-editor](url)

**Comment by Aymkdn** [comment]
I'll have to investigate then. I'll try to do it tomorrow, otherwise it will be when I'm back from vacation (aftet November 13).

**Comment by AnassLAMAALAM** [comment]
I need it emergency please

**Comment by Aymkdn** [comment]
If it's urgent, you can look at a paid solution, not a free open source one.

I'll look at it as soon as I can, based on my availability.

**Comment by Aymkdn** [comment]
I've fixed it in v2.4.9
