### ISSUE TITLE
Single quote or apostrophes

### ISSUE THREAD

**Issue by NigelRoth** [Aymkdn/html-to-pdfmake#157]
Could you please help to be able to use apostrophes in for example {text: 'Europe's call'}

**Comment by Aymkdn** [comment]
Please, provide the HTML code you use to arrive to this result.

**Comment by Aymkdn** [comment]
Please, use Github to comment, and don't reply by email because attachements are not available and the content is unreadable.

**Comment by Aymkdn** [comment]
Your problem is not related to my library but to your code only. I'm closing this issue that is unrelated.
