### ISSUE TITLE
Overriding default styles doesn't work properly.

### ISSUE THREAD

**Issue by guti1690** [Aymkdn/html-to-pdfmake#16]
Hi, first, thanks for the great work you've done here, it's amazing!

I think I found an issue in the way you override the default styles using the options object. I've created a jsbin and added a possible fix to the issue: `applyDefaultStyle(ret, element.tagName.toLowerCase());` The issue happens [here](https://github.com/Aymkdn/html-to-pdfmake/blob/65a9b8e3838a2f62211037913d3b60db7058b174/index.js#L312).

Let me know if you need more details or if I'm doing something wrong.

Jsbin: [https://jsbin.com/tuvabaxaba/edit?js,console](https://jsbin.com/tuvabaxaba/edit?js,console)

**Comment by Aymkdn** [comment]
Nice catch! Thanks for finding where was the problem :)

I've just published v1.1.1 that should fix it !
