### ISSUE TITLE
CSS property "page-break-inside: avoid" ignored

### ISSUE THREAD

**Issue by timhonermann** [Aymkdn/html-to-pdfmake#160]
I am composing a pdf document out of multiple textblocks. I wrapped each textblock in a div with the css property "page-break-inside: avoid". This property seems to get ignored and the page breaks inside a textblock.

My goal is to keep these blocks together since each of these blocks have a title and content.

Example textblock looks like this:
`<div style="page-break-inside: avoid"><h1>My Title</h1><span>Some content here</span></div>`

Is there any other way to achiev this behaviour?

**Comment by Aymkdn** [comment]
Maybe you can find a trick with [`pageBreakBefore`](https://github.com/Aymkdn/html-to-pdfmake#page-break)?

**Comment by timhonermann** [comment]
@Aymkdn I tried it with pageBreakBefore but I don't seem to find a satisfying solution. Right now I just add a pageBreakBefore every textblock except the first one.

With more time I might be able to but this seems to get more complicated than it has to be...

**Comment by Aymkdn** [comment]
Sorry, I don't have any other solution for you 🤷🏼‍♂️

You can check if PDFMake provides a solution for your problem and if it's the case, please let me know.
