### ISSUE TITLE
How to join lines with other styles

### ISSUE THREAD

**Issue by LukaszSzyp** [Aymkdn/html-to-pdfmake#161]
Hi, is some tip to join lines with other styles?
![obraz](https://user-images.githubusercontent.com/54202919/208410639-3aff0d0e-bcb3-4207-8f3f-cd5556a527a4.png)

**Comment by Aymkdn** [comment]
Put it inside a `<DIV>`:
![image](https://user-images.githubusercontent.com/946315/208411190-0283c51c-ac2d-44fc-97bd-4324b2a0b393.png)
