### ISSUE TITLE
Image with custom headers

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/html-to-pdfmake#166]
> I've just created v2.3.0 with the new option [`imagesByReference`](https://github.com/Aymkdn/html-to-pdfmake#imagesbyreference)
> 
> I partially tried it, so feel free to give it a try and let me know if it works correctly.

Hi @Aymkdn 
Is there a way to pass custom headers as well?
Since there is an option to send custom headers in the [pdfmake](https://pdfmake.github.io/docs/0.1/document-definition-object/images/).

_Originally posted by @ankesh-paramanik in https://github.com/Aymkdn/html-to-pdfmake/issues/109#issuecomment-1400426711_

**Comment by Aymkdn** [comment]
> Is there a way to pass custom headers as well?

Not at this time. I'll have to check what it is.

**Comment by ankesh-paramanik** [comment]
Thanks for your response.
I have a requirement in my project, it would be helpful if this feature could be added.

**Comment by Aymkdn** [comment]
It's now available in v2.4.14 – see [the documentation](https://github.com/Aymkdn/html-to-pdfmake#imagesbyreference):
![image](https://user-images.githubusercontent.com/946315/214081591-7ce767ba-8241-4c52-b16f-923b14ad8937.png)

That should do the trick.

**Comment by ankesh-paramanik** [comment]
Thank you so much!
