### ISSUE TITLE
Is it possible to get rid of the associated style-class called html-tagname

### ISSUE THREAD

**Issue by Hibrix-net** [Aymkdn/html-to-pdfmake#168]
Hello,

I created a complex table layout and I see every single element including stuff like that: `"style": ["html-td", "html-tr", "html-tbody", "html-table"]`

Is it possible to avoid those classes to be included and simply include the ones I define in the html?

Many thanks,

**Comment by Aymkdn** [comment]
Right now, no it's not possible. But tomorrow I can add an option for that.

**Comment by Hibrix-net** [comment]
> Right now, no it's not possible. But tomorrow I can add an option for that.

Amazing. Many thanks for the super quick answer + solution.

**Comment by Aymkdn** [comment]
I just released v2.4.16. You can now pass the option `removeTagClasses:true` to not include these classes in the output.

**Comment by Hibrix-net** [comment]
> I just released v2.4.16. You can now pass the option `removeTagClasses:true` to not include these classes in the output.

Many thanks.
