### ISSUE TITLE
Class in parent its been repeated in every children

### ISSUE THREAD

**Issue by Hibrix-net** [Aymkdn/html-to-pdfmake#169]
Hello,

You can check it very easily just by putting e.g.:
```
<table class="table-wrapper">
  <tr>
    <td>One</td>
    <td>Two</td>
  </tr>
  <tr>
    <td>Three</td>
    <td>Four</td>
  </tr>
  <tr>
    <td>Five</td>
    <td>Six</td>
  </tr>
</table>
```

... in the online demo playground: https://aymkdn.github.io/html-to-pdfmake/index.html

See only `<table>` has a class, but in the result the `table-wrapper` class is copied down to every single children.
It doesn't matter if it's a `<table>` or a different HTML tag, the result is always the same.

Is this a bug?

Kind regards,

**Comment by Aymkdn** [comment]
It's not a bug. We need to do it to apply the parent style to the children.

**Comment by Hibrix-net** [comment]
Thanks, but what if I need to apply a class to the parent only then?

**Comment by Aymkdn** [comment]
It's like CSS. The parent style is applied to the children. So you need a child class to override the properties applied by the parent.

You can also remove the unwanted classes by manipulating the object returned by `html-to-pdfmake`.

Use your imagination 😉

**Comment by Hibrix-net** [comment]
Ok, I'll think about it. I precisely wanted to avoid the further object manipulation, but I'll probably do the override class work at the end.

Many thanks,

**Comment by Hibrix-net** [comment]
Sorry again, but I've been tried hard for a long and it's been nearly impossible to override the classes, since all is simply copied to the rest of the elements and we don't have any "!important" here or similar to play with.

Apart of the object manipulation, that I will really avoid (I feel it's super-hacky and not very performant) do you have any suggestion in order for me to simply put a bottom margin in each of the boxes that compose my layout?

Thanks,

**Comment by Aymkdn** [comment]
Please, provide some HTML code with related CSS to show me the expected result.

It's Saturday night here and I've diner with friends, so I'll check your example tomorrow.

**Comment by Hibrix-net** [comment]
Hi,

Just forget it, I simply changed strategy and forgot classes. I ended up solving it passing the pdfmake margins attribute.

Have a good weekend and bon appetit.
