### ISSUE TITLE
Width style parameter isn't correctly converted if it is a floating point number

### ISSUE THREAD

**Issue by xaniox** [Aymkdn/html-to-pdfmake#17]
Just noticed that floating point numbers are not correctly converted if used inside a _style_ attribute. Instead a whitespace is inserted between predecimal and decimal.

For example

`<img style="width:1051.45px" src="data:image/png;base64,iVBO..."/>`

is being converted to:

`[
  {
    "image": "data:image/png;base64,iVBO...",
    "style": [
      "html-img"
    ],
    "width": "1051 45"
  }
]`

This results in pdfmake not being able to parse the width and detecting it as NaN.

Would be nice if this could be fixed, because otherwise I have to inspect the DOM myself and pre-fix my content before piping it into html-to-pdfmake. :)

**Comment by Aymkdn** [comment]
I'll work on it this week-end as I won't have the time to fix it before that.

**Comment by Aymkdn** [comment]
I think it should be OK now!
