### ISSUE TITLE
Inverse method / pdfMakeToHtml?

### ISSUE THREAD

**Issue by mmikic** [Aymkdn/html-to-pdfmake#170]
Hi guys, love the project, and hats down for the effort. 

Do you have any plan on making an inverse method that would convert a pdfmake docdefinition to HTML? 

In my particular case, I'd like to parse different definitions/styles and present them in HTML, allowing the user to edit certain textual content, and then regenerate a PDF with the new content.

Any suggestions on going about this are appreciated.

**Comment by Aymkdn** [comment]
Hey. There is no team here, just me 😜

And no, I don't have any plan of doing this kind of thing. But feel free to create your own project `pdfmake-to-html` !
