### ISSUE TITLE
window is not defined error on Node

### ISSUE THREAD

**Issue by Kerod-Fresenbet-Gebremedhin2660** [Aymkdn/html-to-pdfmake#172]
`ReferenceError: window is not defined`

Steps to reproduce:

1. install html-to-pdfmake `npm install html-to-pdfmake`
2. convert html to pdf 
 ```
import htmlToPdfmake from "html-to-pdfmake";

const html = "<h1>Hello World</h1>";
```
3. run script

**Comment by Aymkdn** [comment]
If you run it on Node, then please check the example.js

**Comment by Kerod-Fresenbet-Gebremedhin2660** [comment]
Noted, thanyou
