### ISSUE TITLE
Pdf is not generated when generating table header and columns within a condition

### ISSUE THREAD

**Issue by ilhamkaddourii** [Aymkdn/html-to-pdfmake#173]
![Screenshot from 2023-03-15 18-48-08](https://user-images.githubusercontent.com/84908594/225381623-f09ccc50-008f-45ea-af26-9ef512aab4f8.png)
when i have a table headers and columns that are populated based on conditions on html, it throws this error. I am trying to have two header rows which don't have same amount of ths

**Comment by ilhamkaddourii** [comment]
<table>
  <thead>
    <tr>
      <th>head1</th>
      <th>head2</th>
      <th>head3</th>
      <th>head4</th>
      <th>head5</th>
      <th>head6 </th>
      <th>head7</th>
    </tr>
    <tr>
      <th>head11</th>
      <th>head12</th>
      <th>head13</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>dd</td>
      <td>dd</td>
      <td>dd</td>
      <td>dd</td>
      <td>dd</td>
      <td>dd</td>
      <td>dd</td>
    </tr>
    <tr>
      <td>dd</td>
      <td>dd</td>
      <td>dd</td>
    </tr>
  </tbody>
</table>

**Comment by Aymkdn** [comment]
No, sorry, I won't support this kind of code.
