### ISSUE TITLE
How to add Tailwindcss to html i'm adding that via CDN in head, but still CSS is not taking

### ISSUE THREAD

**Issue by Raghu-sphereit** [Aymkdn/html-to-pdfmake#178]
<head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link
        href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
        rel="stylesheet"
        />
    </head>

**Comment by Aymkdn** [comment]
It's not how it works. You cannot load a CSS stylesheet.

This library converts the HTML only, and eventually some `style`. It will also associate the CSS class names to the node, but it's then your job to provide the style associated to the CSS classes.

Please, read the documentation and look at the example.
