### ISSUE TITLE
Text inside a <pre> tag is flattened

### ISSUE THREAD

**Issue by GameDungeon** [Aymkdn/html-to-pdfmake#184]
In HTML the \<pre> tag is a preformatted text tag. All of the text inside it is supposed to stay in the same spot. Currently, the whitespace is being stripped and newlines removed, which breaks the functionality of the tag. This behavior makes it very difficult to, for example, display HTML syntax in the pdf as it all gets flattened into a single line.

**Comment by GameDungeon** [comment]
Testing it using your pages, this works in the HTML viewer and then is flattened in the generated PDF.

```
<div>
  <h1>Pre Tags</h1>
  <p>This is some sample CSS:</p>

  <pre>
      a { 
          text-decoration: none; 
      }
  </pre>
</div>

```

**Comment by Aymkdn** [comment]
That should now work with v2.4.21

**Comment by GameDungeon** [comment]
Thanks for making a change so quickly. One thing to note, pre tags apply their functionality to other tags inside them. 

This is a very common pattern that does not quite work yet. 

<div>
  <h1>Pre Tags</h1>
  <p>This is some sample CSS:</p>

  <pre><code>
a { 
    text-decoration: none; 
}
  </code></pre>
</div>

**Comment by Aymkdn** [comment]
OK, I've just added `preserveLeadingSpaces:true` to all the children of a `PRE`. I'm not sure it's the expected behavior 🤷‍♂

**Comment by GameDungeon** [comment]
That's similar to how it works in the spec, so that will probably be good enough generally. Thanks a ton.
