### ISSUE TITLE
Treat <canvas> as an Image

### ISSUE THREAD

**Issue by GameDungeon** [Aymkdn/html-to-pdfmake#186]
Treating canvas elements as images would allow dynamic js generated images as a way to make up for how more complex HTML isn't possible in PDFMake.

I would provide an example for your renderer, but it does not support JS, which is needed to draw onto the canvas.

It is rather simple to extract the image form a canvas as can be seen [here.](https://stackoverflow.com/questions/10257781/can-i-get-image-from-canvas-element-and-use-it-in-img-src-tag)

**Comment by Aymkdn** [comment]
That doesn't seem that simple.... Did you check other projects? None is doing it?

And yes, please provide examples.

**Comment by GameDungeon** [comment]
I have some time today, and I was going to do a PR. There is one issue with this idea. You need an actual reference to the canvas object instead of just a string as you can have with everything else. Figuring out that, I could make a PR.

**Comment by GameDungeon** [comment]
I ended up doing this on my end. I realize this is a bit out of scope for this lib.
