### ISSUE TITLE
ol-li alignment

### ISSUE THREAD

**Issue by its-ratikant** [Aymkdn/html-to-pdfmake#187]
I have ordered list which has more than 10 items, I want all the list items to be aligned right as default (this is also default HTML behavior)

![image](https://github.com/Aymkdn/html-to-pdfmake/assets/77279630/f8561598-d1d0-4fe3-84cf-2839db3e5e05)

I need the numbering like this:

![image](https://github.com/Aymkdn/html-to-pdfmake/assets/77279630/4db18000-639b-4f70-aba0-320b8f6d1d89)

**Comment by Aymkdn** [comment]
The result is generated by [PDFMake](https://github.com/bpampuch/pdfmake), so it's out of my control. Please, check with the [PDFMake](https://github.com/bpampuch/pdfmake) owner.
![image](https://github.com/Aymkdn/html-to-pdfmake/assets/946315/4f097446-c8ea-4f7b-a84a-27608c838228)

**Comment by its-ratikant** [comment]
Oh ok. cool. Thanks a lot for the update!!
