### ISSUE TITLE
 <td> rowspan break the pdfMake

### ISSUE THREAD

**Issue by IvanKYW** [Aymkdn/html-to-pdfmake#189]
Hi, when `<td>` in second row use `rowspan` like this will break the pdfMake:
```
<table style="border-collapse: collapse; width: 100%; height: 48px;" border="1">
   <tbody>
      <tr style="height: 24px;">
         <td >&nbsp;</td>
         <td >&nbsp;</td>
         <td >&nbsp;</td>
      </tr>
      <tr style="height: 24px;">
         <td rowspan="2">&nbsp;</td>
         <td rowspan="2">&nbsp;</td>
         <td rowspan="2">&nbsp;</td>
      </tr>
      <tr></tr>
   </tbody>
</table>
```
The html is generate by [TinyMCE](https://www.tiny.cloud/) editor by create a three rows table and `rowspan` last two, it can also be reproduce in [demo](https://aymkdn.github.io/html-to-pdfmake/index.html) page.

Thank you for building this library!

**Comment by Aymkdn** [comment]
I don't see the point of creating this kind of code… It might be HTML valid, but the visual result is pointless, no?

It might be tricky to fix… I'll check now if I can find a solution.

**Comment by IvanKYW** [comment]
Sorry, I found that multiple empty `tr` will break the fix
```
<table>
   <tbody>
      <tr>
         <td>A</td>
         <td>B</td>
         <td>C</td>
      </tr>
      <tr>
         <td rowspan="3">AA</td>
         <td rowspan="3">BB</td>
         <td rowspan="3">CC</td>
      </tr>
      <tr></tr>
      <tr></tr>
   </tbody>
</table>
```
Some of our client use `rowspan` instead of delete rows when there's more rows than needed in the end leads to the pointless code.

I understand it's weird so if you think the fix is too ugly please just ignore it, thanks.

**Comment by Aymkdn** [comment]
I've just published v2.4.24 that should support multiple `TR` like that.

BTW, if you use this library as a commercial product, it would be nice to make a [small donation](https://github.com/Aymkdn/html-to-pdfmake#donate) (no obligation of course) 😍

**Comment by IvanKYW** [comment]
Thank you for the quick help again!

We are non-profit organization developing system for internal usage, this library indeed helps us a lot! I've make a little donation to support.

**Comment by Aymkdn** [comment]
Thank you very much 🙏
