### ISSUE TITLE
Adding colspan to th giving _minWidth error

### ISSUE THREAD

**Issue by SudeshAK** [Aymkdn/html-to-pdfmake#19]
Hi ,
I have a table with below code
 `<table  class='table table-sm table-bordered table-responsive-sm custom-border'>
                                <thead class='table-light'>
                                    <tr>
                                        <th colspan="2">Header</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Data1</td>
                                        <td>Data2</td>
                                    </tr>
                                </tbody>
                            </table>`

The  output of above html will be :
 <table  class='table table-sm table-bordered table-responsive-sm custom-border'>
                                <thead class='table-light'>
                                    <tr>
                                        <th colspan="2">Header</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Data1</td>
                                        <td>Data2</td>
                                    </tr>
                                </tbody>
                            </table>
When I converted this html to pdf then I am getting below error

` ERROR TypeError: Cannot read property '_minWidth' of undefined
    at getMinMax (pdfmake.js:61732)
    at extendWidthsForColSpans (pdfmake.js:61706)
    at DocMeasure.measureTable (pdfmake.js:61615)
    at pdfmake.js:61081
    at StyleContextStack.auto (pdfmake.js:18428)
    at DocMeasure.measureNode (pdfmake.js:61068)
    at DocMeasure.measureVerticalContainer (pdfmake.js:61311)
    at pdfmake.js:61075
    at StyleContextStack.auto (pdfmake.js:18428)
    at DocMeasure.measureNode (pdfmake.js:61068`

**Comment by Aymkdn** [comment]
I'm working on a fix right now. It should arrive in a few minutes or so !

**Comment by Aymkdn** [comment]
It should be now fixed with v1.1.3

**Comment by SudeshAK** [comment]
Yes... Its working.. thanks for the help

**Comment by SudeshAK** [comment]
@Aymkdn I have my html with bootstrap 4 as css but this css is not applied when pdf is downloaded is there any way to do that?

**Comment by Aymkdn** [comment]
You have to redefine the classes you want to use in the `styles` block of your definition : https://github.com/Aymkdn/html-to-pdfmake#css-class-and-style

**Comment by SudeshAK** [comment]
Hi @Aymkdn 
_minWidth error occurs if we have colspan like this in the table

<table >
    <tr>
        <th colspan='2'>
            h1
        </th>
        <th colspan='3'>
            h2
        </th>
    </tr>
    <tr>
        <td>
            h1data
        </td>
        <td>
            h2data
        </td>
        <td>
            h3data
        </td>
        <td>
            h4data
        </td>
        <td>
            h5data
        </td>
    </tr>
</table>

**Comment by Aymkdn** [comment]
It should now be fixed with v1.1.4

**Comment by SudeshAK** [comment]
Thanks @Aymkdn it is working

**Comment by SudeshAK** [comment]
@Aymkdn now I have  2 table in the html, I want one page break to be added so that one table displays on one page and the second on the second page.How to do that?
