### ISSUE TITLE
row break between pages

### ISSUE THREAD

**Issue by Nabinsharma123** [Aymkdn/html-to-pdfmake#190]
![Capture](https://github.com/Aymkdn/html-to-pdfmake/assets/73181064/23ef02fb-7f24-4916-85e0-82ee8ea5ef1e)

there is a property to fix this in pdfmake
`dontBreakRows: true,`
my question is how i use this in `htmlToPdfmake()` ?

**Comment by Aymkdn** [comment]
What about using `data-pdfmake` https://github.com/Aymkdn/html-to-pdfmake#special-properties ?

I'm on my phone and I don't know where `dontBreakRows` is supposed to be used....

**Comment by Nabinsharma123** [comment]
I found the property here
[https://stackoverflow.com/a/48929066](https://stackoverflow.com/a/48929066)

**Comment by Aymkdn** [comment]
Yes, so check the link I provided.
