### ISSUE TITLE
How to arrange the pictures in one line, one after another?

### ISSUE THREAD

**Issue by a-grekhnev** [Aymkdn/html-to-pdfmake#191]

**Comment by GameDungeon** [comment]
I know that's generally kinda painful to do in pdfmake. Support for flexbox would be pretty cool (and achieve this), but I understand how hard it would be to implement.

**Comment by Aymkdn** [comment]
It is too complex to implement flexbox. Sorry.

**Comment by GameDungeon** [comment]
I'm not the person who created this issue, that's just what came to mind as far as aligning images. I do understand flexbox being far to complex to implement though. Also, thanks for maintaining this lib :)

**Comment by a-grekhnev** [comment]
I did it through a table. Thank you.
