### ISSUE TITLE
Support for header / footer

### ISSUE THREAD

**Issue by grizlizli** [Aymkdn/html-to-pdfmake#195]
Hi, 

Is there a support for header / footer of the page?

As I can see, PDFmake has a support for headers and footers but I don't see support in your awesome library.

Any plans to support that?

Thanks!

**Comment by Aymkdn** [comment]
My lib converts HTML to PDFMake syntax… There is no `header` or `footer` in HTML that would match the same kind of thing in a PDF document…

So I'd recommend to just add the `header` and `footer` after the HTML has been converted. Except if you have a good example of HTML to use, and how the PDFMake will look like, and how the PDf will render?

**Comment by grizlizli** [comment]
Thanks, @Aymkdn. Makes sense. 

Unfortunately, I do not have a good example how it can be used with the HTML template.

**Comment by Aymkdn** [comment]
OK, so I'll assume your ask is not feasible. Have a good day.

**Comment by grizlizli** [comment]
Thanks, @Aymkdn. You too!
