### ISSUE TITLE
Adding extra white space in pdf.

### ISSUE THREAD

**Issue by sanketjagtap1** [Aymkdn/html-to-pdfmake#198]
Hi,

Getting extra blank space in my pdf. Can you please resolve this issue.

<img width="1054" alt="Screenshot 2023-11-09 at 12 18 26 PM" src="https://github.com/Aymkdn/html-to-pdfmake/assets/94338738/1fb8ad32-1844-48a5-a4bf-bf034f3d9381">

**Comment by Aymkdn** [comment]
Did you try the remove blanks option? https://github.com/Aymkdn/html-to-pdfmake#removeextrablanks

**Comment by sanketjagtap1** [comment]
Yes I tried {removeExtraBlanks:true} this but still facing the same issue.

**Comment by Aymkdn** [comment]
Please, share the HTML code and Javascript code too.

**Comment by sanketjagtap1** [comment]
Actually it's companies agreement html code can't share.

**Comment by Aymkdn** [comment]
Try to provide a generic example to replicate the issue, then.

You could also check if this is not due to some empty tags, or the default margins due to some tags.

**Comment by sanketjagtap1** [comment]
There is no empty tags or margin. Using this code from last 2 years it was working fine this packages. From last few months I'm facing this issue.

**Comment by Aymkdn** [comment]
Sorry, but if I don't have any replicable code, I cannot help.
