### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by WayneBarnard** [Aymkdn/html-to-pdfmake#20]
Hi

Do you have support for Angular?
If I try to run it, I get the following error:
Object(...) is not a function

I try to import it like this:
import { htmlToPdfMake } from 'html-to-pdfmake';

And then run it like this:
const result = htmlToPdfMake('<div>test</div>');

Thanks!

**Comment by Aymkdn** [comment]
It's simply : 
```
import htmlToPdfMake from 'html-to-pdfmake'
```

**Comment by WayneBarnard** [comment]
Yata!
Thank you so much!!!
