### ISSUE TITLE
lineHeight property handling

### ISSUE THREAD

**Issue by lcgiry** [Aymkdn/html-to-pdfmake#201]
Hello,

First of all, thank you for your very helpful work.

I noticed that pdfmake offers a lineHeight style property. Are you planning to handle it as well by any chance?

Thanks

**Comment by Aymkdn** [comment]
Maybe. I need to investigate how I can convert the CSS values to a value that would render similar with PDFMake.

**Comment by Aymkdn** [comment]
I think I'll restrict it to a number (unitless) only. It seems to be the preferred way to do it based on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height).

Then a `line-height:normal` will be ignored, but any other number will be just passed to `lineHeight` in PDFMake.

**Comment by Aymkdn** [comment]
Actually, I went through my code, and `lineHeight` is already supported :-)

**Comment by lcgiry** [comment]
Oh great thanks.

I don't think I saw it in your npmjs documentation but never mind, I'll try it !

**Comment by Aymkdn** [comment]
Indeed, it was missing on the README page. I've just added it (but it will only be visible on the NPM page when I'll publish a new version).
