### ISSUE TITLE
Issue with list items not rendering

### ISSUE THREAD

**Issue by gallow** [Aymkdn/html-to-pdfmake#203]
Hi,

Thanks for writing this library!
I'm having an issue where some items in a list are not rendered by pdfmake. The HTML is generated by ngx-editor (https://www.npmjs.com/package/ngx-editor)

If I use html-to-pdfmake on the following html:

`<h1>Test headline</h1><ol><li><p>test1</p><ul><li><p>test2</p><ul><li><p>test3</p></li></ul></li><li><p>test4</p></li><li><p>test5</p></li><li><p>test6</p></li></ul><ul><li><p>test7</p><ul><li><p>test8</p></li></ul></li></ul></li></ol>`

Only "Test headline", "test1", "test7" and "test8" are rendered.

Thanks a lot

**Comment by gallow** [comment]
Thanks! I appreciate it.

**Comment by Aymkdn** [comment]
I've just published v2.5.2 that should fix the issue.
