### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by owen-soak** [Aymkdn/html-to-pdfmake#204]
Seems some work has been done over on https://github.com/bpampuch/pdfmake/issues/74 to provide a way to encourage vertical alignment within tables, is this something that could be ported over to this package?

**Comment by Aymkdn** [comment]
There are dozens of comments in this issue of PDFMake…

It looks like the vertical alignment is **not** a native option of PDFMake, and a hack must be used. So it's not ideal…

I could consider it, but I need your help. Please, provide a working example:
  1. The HTML code
  2. How the PDFMake JSON should represent it
  3. The final/excepted render in PDF

I don't have time to go through all the comments there, then try things, see what works or not, and so on.

Thank you
