### ISSUE TITLE
How to add page break

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/html-to-pdfmake#21]
@Aymkdn now I have  2 table in the html, I want one page break to be added so that one table displays on one page and the second on the second page.How to do that?

_Originally posted by @SudeshAK in https://github.com/Aymkdn/html-to-pdfmake/issues/19#issuecomment-546676043_

**Comment by Aymkdn** [comment]
I see two options:
  1. To use the `pageBreakBefore` function from PDFMake: https://pdfmake.github.io/docs/document-definition-object/page/
  2. To modify `html-to-pdfmake` to support a CSS class *"pdf-pagebreak-before"* or *"pagebreak-after"* which would add a `pageBreak:before/after` tag

I'd say that the best approach is to use option 1... But I never used this solution and I don't know how hard it will be.

@SudeshAK Could you try option 1, and let me know what you think?

**Comment by SudeshAK** [comment]
@Aymrekdn currently when I console  currentNode I can see only 6 attribute by default coming, as per the example given If we can set another attribute `headlineLevel`  we can add a page break
`pageBreakBefore: function(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
     console.log(currentNode);
  }`

**Comment by Aymkdn** [comment]
There is also option 3 : modify the object returned by `html-to-pdfmake` to insert the `pageBreak` in the desired location.

But options 1 and 3 are not easy/practical I think... Let me see if I can add a special CSS class which will add the `pageBreak` when set for an element.

**Comment by Aymkdn** [comment]
Actually, `pageBreakBefore` works well and I don't think anything else needs to be added to this library. I'll update `example.js` to add a page break example.

**Comment by Aymkdn** [comment]
See there: https://github.com/Aymkdn/html-to-pdfmake#page-break

**Comment by SudeshAK** [comment]
@Aymkdn yes it works.. thanks..
