### ISSUE TITLE
Copying and pasting the text "finally" from the PDF and the letter "i" is not included when pasted

### ISSUE THREAD

**Issue by mfrezghi** [Aymkdn/html-to-pdfmake#211]
I was looking through the documentation to see if I could utilize this tool and found a small bug in the demo page https://aymkdn.github.io/html-to-pdfmake/index.html

I'm not sure if the demo is outdated or not, but when I download the PDF from the demo, everything looks okay. But when I copy the text from the PDF and paste it elsewhere, the letter 'i' disappears. For example, 'finally' becomes 'fnally'.

**Comment by Aymkdn** [comment]
The copy&paste works just fine with me. Also, the PDF is produced by PDFMake: my library is only transforming the HTML to PDFMake code.
