### ISSUE TITLE
React native 

### ISSUE THREAD

**Issue by dragospeta** [Aymkdn/html-to-pdfmake#216]
Hi, i'm using this beautiful library on my frontend app and i want to use it on a react native mobile app too. (Expo 51)

I'm using the same code, i can even try `htmlToPdfmake('<div></div>')`, but in react native i get: TypeError: Cannot read property 'prototype' of undefined. (it's located at var parser = new this.wndw.DOMParser();).

I suppose DOMParser is also undefined in react native. Is there a workaround to this? I tried to attach some library parsers to window DOMParser without success.

**Comment by Aymkdn** [comment]
You need to pass DOMParser using the additional parameter as explained here https://github.com/Aymkdn/html-to-pdfmake?tab=readme-ov-file#window

Is it what you did using the library parsers?

Something like `htmlToPdfmake(html, {window:{DOMParser:whateverLibraryParser}}) `

**Comment by dragospeta** [comment]
Yes, i tried to add different parsers but i get different errors, meaning that those parsers might have a slightly different implementation than default DOMParser. I guess i have to start debugging more and investigate further as soon as i find some free time.

**Comment by Aymkdn** [comment]
Did you try JSDom as explained [in this example](https://github.com/Aymkdn/html-to-pdfmake#use-with-node)?

Sorry, I cannot do more than that… Please, comment it if you find a solution: it could help someone else.

**Comment by dragospeta** [comment]
The package at "node_modules/jsdom/lib/api.js" attempted to import the Node standard library module "path".
It failed because the native React runtime does not include the Node standard library.

Don't worry, i'll see what i can do and return if i find a solution. Thanks for your time!

**Comment by c-goettert** [comment]
@dragospeta did you make any progress on this? I am thinking about trying the same path.
