### ISSUE TITLE
Floating is not applied 

### ISSUE THREAD

**Issue by SudeshAK** [Aymkdn/html-to-pdfmake#22]
Hi @Aymkdn I was applying styling like this `style="color:red;float:right"` only color is applied in the pdf float is not applied.

**Comment by Aymkdn** [comment]
This framework is limited to what PDFMake can do. Also I think it cannot perfectly replicate a complex design. It's good for basic HTML but not for fancy CSS. You'll have to modify your HTML in order to make it work in the PDF (for example by using a TABLE to have some stuff align on the right).

**Comment by SudeshAK** [comment]
Ok @Aymkdn.. another thing I have a long text in my table instead of text coming to the next line it is printing it one a single line

**Comment by Aymkdn** [comment]
Again, this is not part of this module scope.... This module only translates HTML code to PDFMake code. The design/CSS/style must be managed by you, as well as the possible tweaks on the code returned by `html-to-pdfmake`
