### ISSUE TITLE
PDFmake does not support the rgba format, so black text displayed as a blue text

### ISSUE THREAD

**Issue by fahmi-nugroho** [Aymkdn/html-to-pdfmake#221]
**Provide the HTML code**
`<ul><li><span style=\"background-color:rgb(255,255,255);color:rgba(0,0,0,0.87);\">Sampel AGD curiga darah vena, jika tidak sesuai klinis mohon sampel ulang.</span></li></ul>`

**Describe the bug**
Result:
`
[
    {
        "nodeName": "UL",
        "marginBottom": 5,
        "marginLeft": 5,
        "style": [
            "html-ul"
        ],
        "ul": [
            {
                "text": [
                    {
                        "text": "Sampel AGD curiga darah vena, jika tidak sesuai klinis mohon sampel ulang.",
                        "nodeName": "SPAN",
                        "background": "#ffffff",
                        "color": "rgba(0,0,0,0.87)",
                        "style": [
                            "html-span",
                            "html-li",
                            "html-ul"
                        ]
                    }
                ],
                "nodeName": "LI",
                "style": [
                    "html-li",
                    "html-ul"
                ]
            }
        ]
    }
]
`
![image](https://github.com/user-attachments/assets/59889e09-3c65-4deb-8324-4ece77626a9a)

**Comment by Aymkdn** [comment]
This is odd. The rgba is supported... I'll check later.

**Comment by Aymkdn** [comment]
The code was correctly providing the current # code to PDFMake, but PDFMake doesn't support RGBA.

Now, the `rgba` value will be converted to a `rgb` color + the `opacity` of the text. It should work this way.

The v2.5.12 has just been released with the patch.

**Comment by fahmi-nugroho** [comment]
thank you, for the update
