### ISSUE TITLE
Feature request: support for columns

### ISSUE THREAD

**Issue by mualala** [Aymkdn/html-to-pdfmake#226]
Please support columns tag, as img takes up one line and sometimes we want img and other elements to be displayed on the same line

**Comment by Aymkdn** [comment]
Please, provide HTML code and the expected result.

**Comment by mualala** [comment]
```
<div style="display: flex;justify-content: start;">
    <img src="https://fastly.picsum.photos/id/1008/200/200.jpg?hmac=I0T_cpYR-61pUlB0jVB4I5B7tL0fvzN5MgslAOirM50">
    <img src="https://fastly.picsum.photos/id/866/200/300.jpg?hmac=rcadCENKh4rD6MAp6V_ma-AyWv641M4iiOpe1RyFHeI">
</div>`
<div style="display: flex;justify-content: start;">
    <img src="https://fastly.picsum.photos/id/1008/200/200.jpg?hmac=I0T_cpYR-61pUlB0jVB4I5B7tL0fvzN5MgslAOirM50">
    <img src="https://fastly.picsum.photos/id/866/200/300.jpg?hmac=rcadCENKh4rD6MAp6V_ma-AyWv641M4iiOpe1RyFHeI">
</div>
```
<div style="display: flex;justify-content: start;">
    <img src="https://fastly.picsum.photos/id/1008/200/200.jpg?hmac=I0T_cpYR-61pUlB0jVB4I5B7tL0fvzN5MgslAOirM50">
    <img src="https://fastly.picsum.photos/id/866/200/300.jpg?hmac=rcadCENKh4rD6MAp6V_ma-AyWv641M4iiOpe1RyFHeI">
</div>

The above code is on one line in HTML, but it will be displayed on two lines in PDF. Now I want it to be on one line. How can it be feasible? I don't know if customTag can support it?

**Comment by Aymkdn** [comment]
I cannot support `display:flex`. The easier way, in that case, is to use a `<table>` and put the images in one row `‹tr>`
