### ISSUE TITLE
Bold/Strong can't be display in Link

### ISSUE THREAD

**Issue by aweikalee** [Aymkdn/html-to-pdfmake#227]
**Provide the HTML code**
```html
<a href="#">abc <strong>def</strong></a>
```

**Describe the bug**
`def`  should be rendered, but it will be remove.

**Comment by Aymkdn** [comment]
I'm looking at it now.

**Comment by Aymkdn** [comment]
It should be fixed with v2.5.14

**Comment by aweikalee** [comment]
Thanks
