### ISSUE TITLE
Newline after numbered list item

### ISSUE THREAD

**Issue by Hoogkamer** [Aymkdn/html-to-pdfmake#229]
**Provide the HTML code**
`<ol><li><strong style="background-color: rgb(255, 255, 255); color: rgb(34, 34, 34);">Number 1</strong><span style="background-color: rgb(255, 255, 255); color: rgb(34, 34, 34);">:</span><ul><li><span style="background-color: rgb(255, 255, 255); color: rgb(34, 34, 34);">Item</span></li></ul></li></ol>`

**Describe the bug**
It adds an extra newline

![image](https://github.com/user-attachments/assets/83e7e28c-2377-4956-99b9-01850ca95703)

![image](https://github.com/user-attachments/assets/69424f53-65ab-4bd3-8c27-0c3ceebde861)

 And thanks for this nice package!

**Comment by Aymkdn** [comment]
Let me have a look and get back to you.

**Comment by Aymkdn** [comment]
I've just published v2.5.16 that should fix it.
