### ISSUE TITLE
Update example to work with latest pdfmake

### ISSUE THREAD

**Issue by akravchukabto** [Aymkdn/html-to-pdfmake#231]
Hi, firstly, thank you for your work effort at this library.

I have noticed that when using the latest **pdfmake** the example does not work.
Line
`pdfMake.vfs = pdfFonts.pdfMake.vfs;`
throughs error
`Uncaught TypeError: Cannot read properties of undefined (reading 'vfs')`
as I found in this comment #https://github.com/bpampuch/pdfmake/issues/2802#issuecomment-2465388008
changing this line to
`pdfMake.vfs = pdfFonts.pdfMake;`
will fix the issue.

I assume there is a need to update example.
Thanks.

**Comment by Aymkdn** [comment]
Thanks. I'll adjust it next week.
