### ISSUE TITLE
Request add `removeExtraBlanks` work with `table`,`tr`,`td` 

### ISSUE THREAD

**Issue by phongtran11** [Aymkdn/html-to-pdfmake#233]
**Provide the HTML code**
Share the HTML code that you try to convert.

<table>
  <tr>
    <td>
      <table>
        <tr style='border: none'>
          <td>test title 1</td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td class="blue">test</td>
  </tr>
</table>

`
var dd = {
  "content": [
    {
      "nodeName": "TABLE",
      "table": {
        "body": [
          [
            {
              "nodeName": "TD",
              "stack": [
                {
                  "text": " " // redundant code
                },
                {
                  "nodeName": "TABLE",
                  "marginBottom": 5,
                  "table": {
                    "body": [
                      [
                        {
                          "text": "test title 1",
                          "nodeName": "TD",
                          "border": [
                            false,
                            false,
                            false,
                            false
                          ]
                        }
                      ]
                    ],
                    "widths": [
                      "auto"
                    ],
                    "heights": [
                      "auto"
                    ]
                  }
                },
               {
                  "text": " " // redundant code
                },
              ]
            }
          ],
          [
            {
              "text": "test",
              "nodeName": "TD",
              "style": [
                "blue"
              ]
            }
          ]
        ],
        "widths": [
          "auto"
        ],
        "heights": [
          "auto",
          "auto"
        ]
      },
      "marginBottom": 5
    }
  ],
  "styles": {
    "green": {
      "color": "green"
    },
    "blue": {
      "color": "green"
    }
  }
}
`

**Describe the bug**
A clear and concise description of what the bug is. What is the result in the PDF, versus what you expected to see.
It will append empty blocks with every  blank space
Any special reason for ignore removeExtraBlanks with table tags. 
In my case also need to remove extra blanks in table tags

**Comment by Aymkdn** [comment]
Fixed in v2.5.19
