### ISSUE TITLE
Table border issue

### ISSUE THREAD

**Issue by pradeepmandalapu** [Aymkdn/html-to-pdfmake#26]
Hi
I am unable to delete table border.
I tried with normal inline css..
I given a class for the table and applied style for the created class as per the document. Still I am not able to remove border.
Can you please help me to sort this issue.

**Comment by Aymkdn** [comment]
Can you provide some code, as well as the result you get and the result you were expected?

I'm currently attending a conference for work and I'm without a computer until Monday so I won't probably be able to provide a solution until then.

**Comment by pradeepmandalapu** [comment]
Thanks for your quick response. I am not able to comment from my office laptop. I am commenting from my phone. I will do from my personal system after some time.
I taken the example.js code and applied border none property to table
And I tried to align the image to right. Both are not worked.

**Comment by pradeepmandalapu** [comment]
Hi ,
I have copied your example.js code and applies some sort of css in multiple ways and also i tried with the approach in the documentation. None of those are worked for me.
**My requirement is i need to change the font name and size  as well as i don't need table borders. I will have pdf data in key and value pair. Key will be in 1 row. data will be in  second row**

I also tried `https://aymkdn.github.io/html-to-pdfmake/index.html`  in this link with the table related piece  of code from your example.js and applied border:none. It is also not worked
Please find the code below. Also attached a screenshot 
![2](https://user-images.githubusercontent.com/9839380/70240046-827b3c80-1792-11ea-949b-6dd6b92377ce.png)

`var pdfMake = require('pdfmake/build/pdfmake');
var pdfFonts = require('pdfmake/build/vfs_fonts');
pdfMake.vfs = pdfFonts.pdfMake.vfs;
var fs = require('fs');
var jsdom = require('jsdom');
var { JSDOM } = jsdom;
var { window } = new JSDOM('');
var htmlToPdfMake = require('html-to-pdfmake');
//var util = require("util");

var html = htmlToPdfMake(`<table border=0>
    <tr>
      <td colspan="3">Table with <b>widths=[100,"*","auto"]</b> and <b>heights=40</b></th>
    </tr>
    <tr>
      <td>column1</td>
      <td>column2</td>
      <td>column3</td>
    </tr>
  </table>
  
  another style
  <table style="border:none">
    <tr>
      <td colspan="3">Table with <b>widths=[100,"*","auto"]</b> and <b>heights=40</b></th>
    </tr>
    <tr>
      <td>column11</td>
      <td>column12</td>
      <td>column13</td>
    </tr>
  </table>
  `,
  { window: window }
);

//console.log(util.inspect(html, {showHidden: false, depth: null}))

var docDefinition = {
  content: [ html ]
};

var pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBuffer(function(buffer) {
  fs.writeFileSync('examplepdf.pdf', buffer);
  console.log('--> example.pdf');
});
`

**Comment by pradeepmandalapu** [comment]
This is how I wrote the code, in above comment.
![2](https://user-images.githubusercontent.com/9839380/70240338-0cc3a080-1793-11ea-9722-34e2292266d4.png)

**Comment by Aymkdn** [comment]
Thanks for sharing code. I'll check it as soon as I get a computer, probably by Monday.

**Comment by Aymkdn** [comment]
To have no borders on a table, you have to use the `layout` option `noBorders`, as described in the [PDFMake documentation](https://pdfmake.github.io/docs/document-definition-object/tables/). It's at the same level than the `<table>` so you have to apply it to a `<div>`, using the [`data-pdfmake`](https://github.com/Aymkdn/html-to-pdfmake#special-properties) properties like the below code:
```html
  <div data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}">
    <table><tr><td>Hello</td><td>World</td></tr></table>
  </div>
```

Which will be converted to the below:
```javascript
[
  {
    "table": {
      "body": [
        [
          {
            "text": "Hello",
            "style": [
              "html-td",
              "html-tr"
            ]
          },
          {
            "text": "World",
            "style": [
              "html-td",
              "html-tr"
            ]
          }
        ]
      ]
    },
    "style": [
      "html-table",
      "html-div"
    ],
    "marginBottom": 5,
    "layout": "noBorders"
  }
]
```

**Comment by etoktaev** [comment]
I can't repeat this example.

`<div data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}">
    <table><tr><td>Hello</td><td>World</td></tr></table>
  </div>`

In the log I get the following code:

`[
  { text: '﻿', style: [] },
  { nodeName: 'DIV', stack: [ [Object] ], layout: 'noBorders' }
]`

**Comment by lgregg05** [comment]
I hope this helps someone. I got this to work by doing:
`<table data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}"><tr><td>Hello</td><td>World</td></tr></table>`
Instead of
`  <div data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}">
    <table><tr><td>Hello</td><td>World</td></tr></table>
  </div>`

**Comment by lgregg05** [comment]
I had the same problem and got it to work by moving `data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}"` to the table and removed the outer div.

So, instead of

```
<div data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}">
    <table><tr><td>Hello</td><td>World</td></tr></table>
</div>
```

try

```
<table data-pdfmake="{&quot;layout&quot;:&quot;noBorders&quot;}">
    <tr>
        <td>Hello</td>
        <td>World</td>
    </tr>
</table>
```
