### ISSUE TITLE
css object-fit not supported

### ISSUE THREAD

**Issue by attarepos** [Aymkdn/html-to-pdfmake#29]
i am trying to add object-fit:cover property to image style like this
`<img style="width:200px;height:200px;object-fit:cover"  src="'data:image/jpeg;base64,........'" >`
but it does not take any effect.
Is object-fit css property supported or not

**Comment by Aymkdn** [comment]
No, it's not.

You may want to check the [special properties](https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#special-properties) and the [PDFMake documentation for `img`](https://pdfmake.github.io/docs/document-definition-object/images/) (property `fit`)
