### ISSUE TITLE
Server side error: "window is not defined"

### ISSUE THREAD

**Issue by Bottley** [Aymkdn/html-to-pdfmake#3]
Hi @Aymkdn,

Thank you for creating a very useful package.

I have successfully implemented the package client side, but I am struggling with implementation on the server side (nodejs) firebase cloud functions.

I receive the error "window is not defined" at runtime.

I assume it has something to do with the way I am importing the packages?

`var pdfMake = require("pdfmake/build/pdfmake");
var pdfFonts = require("pdfmake/build/vfs_fonts");
pdfMake.vfs = pdfFonts.pdfMake.vfs;
var htmlToPdfMake = require("html-to-pdfmake");`

**Comment by Aymkdn** [comment]
You have to pass a `window` as a second argument to the function.
You can look at the [test file](https://github.com/Aymkdn/html-to-pdfmake/blob/master/test/unit.js) for an example.

The idea is to use `jsdom` to simulate the `window`:
```javascript
var jsdom = require("jsdom");
var { JSDOM } = jsdom;
var { window } = new JSDOM("");

htmlToPdfMake("<strong>bold word</strong>", window);
```

**Comment by Bottley** [comment]
Perfect! It works wonderfully! 

Thank you
