### ISSUE TITLE
p inside td

### ISSUE THREAD

**Issue by zoozalp** [Aymkdn/html-to-pdfmake#31]
Hi,

I'm having a styling problem with the following html. Can you please help me figure this out?

```
<table border="1">
<tr>
<td>
<p><p> </p></p><p>BEN VE AİLEM</p><p><p> </p></p><p><span style="color: rgb(91, 155, 213);">ICH UND MEINE FAMILIE</span></p><p><p> </p></p><p><span style="color: rgb(91, 155, 213);"> </span></p><p><p> </p></p><p>Tanışma</p><p><p> </p></p><p><span style="color: rgb(91, 155, 213);">Kennenlernen</span></p><p><p> </p></p><p><span style="color: rgb(84, 141, 212);"> </span></p>
</td>
</tr>
</table>
```

The problem also exists in the playground.

![image](https://user-images.githubusercontent.com/2495246/71412296-2fdcc400-265e-11ea-93dc-62fe27663e95.png)

**Comment by Aymkdn** [comment]
Can you replace your `<p></p>` with `<br>`? If yes, then it will work.

If you cannot, then I'll have to take some time to think about it... As it's Christmas holidays I may not have time to check it before at least a few days.

**Comment by zoozalp** [comment]
Nice catch! Content is coming from Quill. I'll try to replace as you suggested on the fly and see how it works.

**Comment by zoozalp** [comment]
It worked for the sample html I posted above but unfortunately it doesn't work for the rest of the document.

Here is another example;

```
<table border="1">
            <tbody>
                <tr>
                    <td align="center" valign="top">
                        <p>TARİH</p>
                        <p style="color: blue;">DATUM</p>
                    </td>
                    <td align="center" valign="top">
                        <p>ÜNİTE VE KONULAR</p>
                        <p style="color: blue;">LEKTIONEN UND THEMEN</p>
                    </td>
                </tr>
            </tbody>
</table>
```

![image](https://user-images.githubusercontent.com/2495246/71417305-aafda480-2675-11ea-9dfc-d82f34e7e41c.png)

**Comment by Aymkdn** [comment]
Ok. I'll review it later this week or sometime next week.

**Comment by Aymkdn** [comment]
It looks like the issue is related to PDFMake and not to my library. Inside cells, we have to use `\n` to have the texte on several lines (based on PDFMake website).

So, I guess you're stuck with using `<br>`. You can inject `<br>` after your `</p>` in your HTML code. For example:
```javascript
yourHTMLcode.replace(/<\/p>\n(\s+)?<p/g,'</p><br><p')
```

It will return (using your last example):
```html
<table border="1">
  <tbody>
    <tr>
      <td align="center" valign="top">
        <p>TARİH</p><br><p style="color: blue;">DATUM</p>
      </td>
      <td align="center" valign="top">
        <p>ÜNİTE VE KONULAR</p><br><p style="color: blue;">LEKTIONEN UND THEMEN</p>
      </td>
    </tr>
  </tbody>
</table>
```

And, once translated by `html-to-pdfmake`:
![Capture](https://user-images.githubusercontent.com/946315/71478955-91ce3280-27f2-11ea-9cdb-2e9da06f8dcc.JPG)
