### ISSUE TITLE
Window is not defined when running on NodeJS

### ISSUE THREAD

**Issue by DutchKevv** [Aymkdn/html-to-pdfmake#36]
Hi there!

Does this module work within NodeJS?? 
I'm getting the following error

```
ReferenceError: window is not defined
server-api    |     at module.exports (/usr/src/app/server-api/node_modules/html-to-pdfmake/index.js:36:60)
```

I can see in the code it expects a window to be present ... 

Thanks!

**Comment by Aymkdn** [comment]
Yes. Look at the example that runs on server side: https://github.com/Aymkdn/html-to-pdfmake/blob/master/example.js

**Comment by DutchKevv** [comment]
Thanks @Aymkdn , working now (y)
