### ISSUE TITLE
Browser fails with pdfmake@0.2.0

### ISSUE THREAD

**Issue by JavaOopAlgoStudent** [Aymkdn/html-to-pdfmake#38]
Hi! I an absolutely new to both JavaScript and html-to-pdfmake. 
I tried to run a html-to-pdfmake browser. It works nice with pdfmake@0.1.57, but with last branch 0.2.0 it fails. 
(I copied 0.2.0 files to my local HD and much simplified index.html. Initial run is OK, but when trying to refresh, it freezes. With 0.1.57 version it works normally.)

**Comment by Aymkdn** [comment]
Hi,

I don't see a v0.2 for PDFMake on https://github.com/bpampuch/pdfmake/releases .... The last release is 0.1.64 🤷🏻‍♂️

**Comment by Aymkdn** [comment]
I'd recommend using the last stable release of pdfmake that is v0.1.64 and not another brunch.

The author of pdfmake says on his repo that v0.2.0 is unstable.

**Comment by JavaOopAlgoStudent** [comment]
Hi,
I found it here https://github.com/bpampuch/pdfmake/ and downloaded it in
ZIP file.
Yes, you are right - the author declares instability. However, I mean it is
better to let you know something may turn wrong.
Best regards,
Josef



pá 14. 2. 2020 v 19:12 odesílatel Aymeric <notifications@github.com> napsal:

**Comment by Aymkdn** [comment]
Yes, thank you!

When the release will be stable I'll do the necessary changes on my package (if needed).
