### ISSUE TITLE
Style personalization

### ISSUE THREAD

**Issue by AccesAmiral** [Aymkdn/html-to-pdfmake#4]
Hello
Nice work
How to personalize font style (Hx, ...), margin of elements (p, div, ...) ?
Can you add examples in documentation (H1 in red 24pt, p with margin-top 12pt, ...) ?
Thanks

**Comment by Aymkdn** [comment]
It's already explained in the doc : https://github.com/Aymkdn/html-to-pdfmake#customize-style

For example for `h1` with red 24pt:
```javascript
var docDefinition = {
  content: [
    html
  ],
  styles:{
    'html-h1':{
      color:'red',
      fontSize:24
    }
  }
};
```
