### ISSUE TITLE
Table layout pdfmake option

### ISSUE THREAD

**Issue by jag-va** [Aymkdn/html-to-pdfmake#42]
Doesn't seem to work when you pass layout:'noBorders' on the data-pdfmake attribute.

**Comment by jag-va** [comment]
I've just customised the index.js to add whatever I have under data-layout="noBorders" etc and set "ret.layout = element.dataset.layout";

**Comment by Aymkdn** [comment]
Can you provide an example of your html code?

**Comment by jag-va** [comment]
@Aymkdn Ah its fine, went back on a previous issue and I saw you commented that you put the data-pdfmake attribute in a div that has the table within it and it will pick it up and add the layout. Works fine! Thanks
