### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by FahdLihidheb** [Aymkdn/html-to-pdfmake#45]
I tried html-to-pdfmake with node and  i get this error `window is not defined`, i tried passing the `global` but it seems that it needs `DOMParser` or something and i have no clue.

**Comment by Aymkdn** [comment]
Check the example : https://github.com/Aymkdn/html-to-pdfmake/blob/master/example.js

**Comment by Aymkdn** [comment]
I'll add a section in the Readme to make it easier to understand.

**Comment by Aymkdn** [comment]
Here you go: https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#use-with-node

I hope it helps.
