### ISSUE TITLE
Unable to process ngx-quill styles

### ISSUE THREAD

**Issue by pragatikerur** [Aymkdn/html-to-pdfmake#47]
Hi, I've used [ngx-quill](https://www.npmjs.com/package/ngx-quill) to let users edit their content and then using html-to-pdfmake (for HTML support) generating the PDF. As I've used ngx-quill the styles are defined as per ngx-quill, html-to-pdfmake doesn't seem to parse them. For example, edited this in my ngx-quill editor, the html form is:  `<p class="ql-align-justify ql-indent-2">hi</p>` after passing this html input to html-to-pdf the indentation didn't work in PDF generated. Is there a way to fix this? Thanks

**Comment by Aymkdn** [comment]
You have to define the style for each class in the PDFMake definition.

Please, read this part of the documenation: https://github.com/Aymkdn/html-to-pdfmake#css-class-and-style

**Comment by pragatikerur** [comment]
There are a lot of styles present in the CSS file of the quill, it is tedious to define each and every class in PDFMake and another thing PDFMake doesn't allow us to define a style like this `ql-align-justify` , the hyphen is a problem I guess.

**Comment by Aymkdn** [comment]
Make sure to use quotes around your classname, like that:
```javascript
var docDefinition = {
 content: [
   html
 ],
 styles:{
   "ql-align-justify":{
     color:'red'
   }
 }
};
```

The purpose of this library is to help generating the PDFMake code for a valid HTML code. It will be too much work to get all the styles from all the classes, then find their equivalent in PDFMake style, and so on.

This lib was a side project and I don't have the bandwidth to work on something that complicated.

If you want to build this complex work, feel free and then submit a pull request: it will be much appreciated :-) 

I'll now close this issue.
