### ISSUE TITLE
How to display Chinese

### ISSUE THREAD

**Issue by SosoCNred** [Aymkdn/html-to-pdfmake#48]
Unable to display Chinese normally

**Comment by Aymkdn** [comment]
Do you have a code example please?

Also it's probably related to PDFMake project, and not mine. See http://pdfmake.org/

**Comment by SosoCNred** [comment]
I've got it. Thank you











------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aymeric"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上6:53
收件人: "Aymkdn/html-to-pdfmake"<html-to-pdfmake@noreply.github.com&gt;; 
抄送: "王祥霖"<1395244089@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Aymkdn/html-to-pdfmake] How to display Chinese (#48)





 
Do you have a code example please?
 
Also it's probably related to PDFMake project, and not mine. See http://pdfmake.org/
