### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by WellBaik** [Aymkdn/html-to-pdfmake#5]
Hi,
is there any way to install with bower ?
Thanks

**Comment by Aymkdn** [comment]
I don't use bower, so I don't know.

**Comment by WellBaik** [comment]
Oh ...
Is there any possibilities to use it with a CDN ?
Thanks

**Comment by Aymkdn** [comment]
> 
> 
> Oh ...
> Is there any possibilities to use it with a CDN ?
> Thanks

I've just created an online demo that permits to convert some html code to the PDFMake version (and with the result shown in a PDF iframe): https://aymkdn.github.io/html-to-pdfmake/index.html

From there you can use the file I created using Browserify: https://github.com/Aymkdn/html-to-pdfmake/blob/master/docs/browser.js

And if you need a CDN, you can use this link: https://cdn.jsdelivr.net/npm/html-to-pdfmake/docs/browser.js

**Comment by Aymkdn** [comment]
By the way, Bower is deprecated: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by WellBaik** [comment]
Thanks for the CDN !!
And I know for Bower, but that's not the priority to upgrade to yarn.
Have a good day
