### ISSUE TITLE
Add fillcolor if TD have backgroundColor

### ISSUE THREAD

**Issue by mcallegario** [Aymkdn/html-to-pdfmake#50]
Dear,

Congratulations for the initiative.
I don't know if it was the best solution, but it solved my problem.
I made the following change to the code to solve the background color problem in TD, as an example:

      <table data-pdfmake="{&quot;widths&quot;:[&quot;*&quot;]}">
         <tbody>
            <tr>
               <td style="background-color: #7a0000;">​​​​&#160;<strong style="color: #ffffff;">Objetivo</strong></td>
            </tr>
         </tbody>
      </table>

![image](https://user-images.githubusercontent.com/44271732/82854212-25a94500-9ede-11ea-90e4-55c27f376550.png)

**Comment by Aymkdn** [comment]
I've just published v1.3.4 that should fix it.
