### ISSUE TITLE
"HR" misbehave on re-render...

### ISSUE THREAD

**Issue by AndonIgnatov** [Aymkdn/html-to-pdfmake#57]
I'm using your awesome script with React.js. 
The issue I encountered is with the `<hr />` element. 

Background:
I've setup a button that will generate a PDF from some content, the issue is that if you click the button multiple times, basically to generate the same report multiple times the `<hr />` keeps adding all this spacing above and to the right of it and with each newly generated instance the gaps are getting bigger.

Here's some code snippet to try to reproduce this:
```javascript
const html = htmlToPdfmake(`
    <div>
      <h1>My title</h1>
      <p>
        This is some example content...
      </p>
      <hr />
    </div>`);

  const docDefinition = {
    content: [
      html,
    ]
  };

  const pdfDocGenerator = () => {
    pdfMake.createPdf(docDefinition).open();
  };

  return (
    <Button onClick={pdfDocGenerator}>Open PDF</Button>
  );
```
Here's some screenshots to demonstrate the issue.

First open:

![image](https://user-images.githubusercontent.com/64331985/85203135-8a876d80-b2d9-11ea-9910-b264f610a28c.png)

Second open:

![image](https://user-images.githubusercontent.com/64331985/85203141-95da9900-b2d9-11ea-9dd9-0af577328cae.png)

Third open:

![image](https://user-images.githubusercontent.com/64331985/85203147-9c691080-b2d9-11ea-8f4b-e9e17de4a052.png)

and so on...
Thanks

**Comment by Aymkdn** [comment]
I'm not at home this weekend so I cannot test, but it's probably something in your code that is causing this issue....

I'll do a test on Monday

**Comment by AndonIgnatov** [comment]
Could be, mind you all other elements work fine it's just the 'hr' and I've not applied any styling to it just to be sure that it's not me, so it's all doing this with default setup.
Regards

**Comment by Aymkdn** [comment]
I tried to reproduce your issue but I cannot.

Can you check the content of `docDefinition` and spot the difference between your first attempt and the second one? That might help understand what's going on.

**Comment by AndonIgnatov** [comment]
Thanks for checking Aymkdn, unfortunately that did not lead to anything, the docDefinition objects in both instances are the same:
![image](https://user-images.githubusercontent.com/64331985/85288327-89824780-b463-11ea-9595-56d7a6c444f4.png)
Any other ideas?

**Comment by Aymkdn** [comment]
Can you check the code coming from `html-to-pdfmake`? Because you're showing how the `docDefinition` looks like after `pdfmake` has changed it. Using something like `JSON.stringify(docDefinition)`.

**Comment by Aymkdn** [comment]
Actually, show `JSON.stringify(html)`, and not `docDefinition`

**Comment by AndonIgnatov** [comment]
OK, we have different results between the first and second open.

Here's the first:

```javascript
JSON.stringify(html): [{"nodeName":"DIV","stack":[{"text":"My title","nodeName":"H1","fontSize":24,"bold":true,"marginBottom":5,"style":["html-h1","html-div"]},{"text":"This is some example content...","nodeName":"P","margin":[0,5,0,10],"style":["html-p","html-div"]},{"nodeName":"HR","margin":[0,12,0,12],"canvas":[{"type":"line","x1":0,"y1":0,"x2":514,"y2":0,"lineWidth":0.5,"lineColor":"#000000"}]}]}] breadcrumbs.ts:103
```
here's the 2nd:

```javascript
JSON.stringify(html): [{"nodeName":"DIV","stack":[{"text":"My title","nodeName":"H1","fontSize":24,"bold":true,"marginBottom":5,"style":["html-h1","html-div"],"_margin":[0,0,0,5],"_inlines":[],"_minWidth":41.09765625,"_maxWidth":79.76953125,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":40,"verticalRatio":0,"horizontalRatio":0}]},{"text":"This is some example content...","nodeName":"P","margin":[0,5,0,10],"style":["html-p","html-div"],"_margin":[0,5,0,10],"_inlines":[],"_minWidth":50.0390625,"_maxWidth":169.1484375,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":78.125,"verticalRatio":0.0500400320256205,"horizontalRatio":0}]},{"nodeName":"HR","margin":[0,12,0,12],"canvas":[{"type":"line","x1":40,"y1":114.1875,"x2":554,"y2":114.1875,"lineWidth":0.5,"lineColor":"#000000"}],"_margin":[0,12,0,12],"_maxWidth":514,"_minWidth":514,"_maxHeight":0,"_minHeight":0,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":114.1875,"verticalRatio":0.09737298035149432,"horizontalRatio":0}]}],"_margin":null,"_minWidth":514,"_maxWidth":514,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":40,"verticalRatio":0,"horizontalRatio":0},{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":78.125,"verticalRatio":0.0500400320256205,"horizontalRatio":0},{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":114.1875,"verticalRatio":0.09737298035149432,"horizontalRatio":0}]}] breadcrumbs.ts:103

```
and the 3rd:

```javascript
JSON.stringify(html): [{"nodeName":"DIV","stack":[{"text":"My title","nodeName":"H1","fontSize":24,"bold":true,"marginBottom":5,"style":["html-h1","html-div"],"_margin":[0,0,0,5],"_inlines":[],"_minWidth":41.09765625,"_maxWidth":79.76953125,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":40,"verticalRatio":0,"horizontalRatio":0}]},{"text":"This is some example content...","nodeName":"P","margin":[0,5,0,10],"style":["html-p","html-div"],"_margin":[0,5,0,10],"_inlines":[],"_minWidth":50.0390625,"_maxWidth":169.1484375,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":78.125,"verticalRatio":0.0500400320256205,"horizontalRatio":0}]},{"nodeName":"HR","margin":[0,12,0,12],"canvas":[{"type":"line","x1":80,"y1":228.375,"x2":594,"y2":228.375,"lineWidth":0.5,"lineColor":"#000000"}],"_margin":[0,12,0,12],"_maxWidth":554,"_minWidth":554,"_maxHeight":114.1875,"_minHeight":114.1875,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":114.1875,"verticalRatio":0.09737298035149432,"horizontalRatio":0}]}],"_margin":null,"_minWidth":554,"_maxWidth":554,"positions":[{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":40,"verticalRatio":0,"horizontalRatio":0},{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":78.125,"verticalRatio":0.0500400320256205,"horizontalRatio":0},{"pageNumber":1,"pageOrientation":"portrait","pageInnerHeight":761.89,"pageInnerWidth":515.28,"left":40,"top":114.1875,"verticalRatio":0.09737298035149432,"horizontalRatio":0}]}] breadcrumbs.ts:103

```

**Comment by AndonIgnatov** [comment]
I see the difference in the canvas:
![image](https://user-images.githubusercontent.com/64331985/85292965-ac642a00-b46a-11ea-825c-92c4f3efd40e.png)

**Comment by Aymkdn** [comment]
It looks like your `html` variable (in the second call) has some values from the first `pdfmake` call… Which is weird based on the code you sent me. Except if you test a code that is not the one you sent in your first comment?

**Comment by AndonIgnatov** [comment]
I'm testing the code I sent you above, but I'm running it within a larger react project, it's not isolated with just 1 file, so it's possible that something else interferes which is strange. It is also strange that only the HR is affected out of all the elements.

I have found a workaround for now simply adding a separator line with underscores. I don't like doing this but it works. 

Have you tried adding perpetrator line with another element applying border for example with your script?

**Comment by AndonIgnatov** [comment]
OK, sounds good, no worries, and thanks for your swift replies. 

Cheers!
