### ISSUE TITLE
error parse table

### ISSUE THREAD

**Issue by JD99** [Aymkdn/html-to-pdfmake#59]
ver 2.0.6

`Uncaught (in promise) TypeError: cells.forEach is not a function
    parseElement http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1
    parseElement http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1
    parseElement http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1
    parseElement http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1
    parseElement http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1
    convertHtml http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1
    exports http://127.0.0.1:8005/static/plugins/jsPDF-1.5.3/html-to-pdfmake.js?v=609:1`

`<table id="table1" class="table-multi table table-striped table-bordered table1 dataTable" role="grid" style="width: 100%;" data-status="2" width="100%" cellspacing="0">
      <thead>
        <tr role="row" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><th rowspan="4" class="sorting_disabled" colspan="1" style="width: 216px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Наименование муниципального района (городского округа)</th><th rowspan="4" class="sorting_disabled" colspan="1" style="width: 237px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Площадь муниципального района (городского округа), км2 (тыс. км2)</th><th data-a-text-rotation="90" rowspan="4" class="sorting_disabled" colspan="1" style="width: 20px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Наименование участкового лесничества</th><th colspan="8" rowspan="1" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Площадь земель, на которых расположены леса</th><th data-a-text-rotation="90" rowspan="4" class="sorting_disabled" colspan="1" style="width: 20px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Лесистость территории, %</th><th colspan="3" rowspan="2" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Запас древесины</th><th colspan="2" rowspan="2" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Кроме того, площадь лесов, в отношении которых лесоустройство не проводилось</th><th rowspan="4" class="sorting_disabled" colspan="1" style="width: 94px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Всего площадь лесов</th></tr>
        <tr role="row" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><th rowspan="3" data-a-text-rotation="90" class="sorting_disabled" colspan="1" style="width: 20px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">всего лесов, в отношении которых имеются материалы лесоустройства</th><th colspan="3" rowspan="1" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">в том числе по целевому назначению лесов</th><th rowspan="3" data-a-text-rotation="90" class="sorting_disabled" colspan="1" style="width: 20px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">лесные  земли</th><th colspan="3" rowspan="1" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">в том числе занятые лесными насаждениями (покрытые лесной растительностью)</th></tr>
        <tr role="row" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><th data-a-text-rotation="90" rowspan="2" class="sorting_disabled" colspan="1" style="width: 44px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">защитные</th><th data-a-text-rotation="90" rowspan="2" class="sorting_disabled" colspan="1" style="width: 44px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">эксплуатационные</th><th data-a-text-rotation="90" rowspan="2" class="sorting_disabled" colspan="1" style="width: 44px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">резервные</th><th data-a-text-rotation="90" rowspan="2" class="sorting_disabled" colspan="1" style="width: 22px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">всего</th><th colspan="2" rowspan="1" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">из них лесными насаждениями с преобладанием древесных пород</th><th data-a-text-rotation="90" rowspan="2" class="sorting_disabled" colspan="1" style="width: 20px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">общий</th><th colspan="2" rowspan="1" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">в том числе лесных насаждений с преобладанием древесных пород</th><th rowspan="2" class="sorting_disabled" colspan="1" style="width: 42px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Всего</th><th rowspan="2" class="sorting_disabled" colspan="1" style="width: 276px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">в том числе занятые лесными насаждениями (покрытые лесной растительностью)</th></tr>
        <tr role="row" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><th data-a-text-rotation="90" class="sorting_disabled" rowspan="1" colspan="1" style="width: 118px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">хвойных</th><th data-a-text-rotation="90" class="sorting_disabled" rowspan="1" colspan="1" style="width: 118px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">твердолиственных</th><th data-a-text-rotation="90" class="sorting_disabled" rowspan="1" colspan="1" style="width: 109px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">хвойных</th><th data-a-text-rotation="90" class="sorting_disabled" rowspan="1" colspan="1" style="width: 109px;" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">твердолиственных</th></tr>
      <tr class="addmy" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">1</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">2</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">3</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">4</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">5</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">6</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">7</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">8</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">9</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">10</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">11</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">12</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">13</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">14</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">15</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">16</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">17</th><th class="text-center" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">18</th></tr></thead>
      <tbody><tr role="row" class="odd" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Белозерское</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">5398</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Конец-Слободское</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">675.0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">675.0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">472.0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">452</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">220</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">69.022</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">31.750</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">31.750</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">675.0</td></tr><tr role="row" class="even" data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Белозерское</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">Итого</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">675.0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">675.0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">472.0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">452</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">220</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">0</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">69.022</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">31.750</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">31.750</td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></td><td data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman">675.0</td></tr></tbody>
      <tfoot><tr data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></tr></tfoot>
    </table>`

**Comment by Aymkdn** [comment]
I'll have to investigate. I'll do it asap.

**Comment by JD99** [comment]
Thanks!

**Comment by Aymkdn** [comment]
Looks like `<tfoot><tr data-b-a-s="thin" data-a-h="center" data-a-wrap="true" data-f-name="Times New Roman"></tr> </tfoot>` is causing the error.

**Comment by Aymkdn** [comment]
It should be fixed with v2.0.8
