### ISSUE TITLE
Single column tables doesn't work

### ISSUE THREAD

**Issue by hiabmicke** [Aymkdn/html-to-pdfmake#6]
Hi and thanks for a nice project!

I was trying out your demo page when I noticed that single column tables does not work.
**Example 1:**
```
<table>
  <tr>
    <td>Single Cell</td>
  </tr>
</table>
```
This throws an error *Uncaught TypeError: Cannot read property 'length' of undefined* in docPrepocessor.js.
However, the problem seems to stem from the conversion from HTML to pdfMake code in index.js/parseElement function, inside the switch case for "table". When only one td is defined the stack property doesn't exist and the body array is not correctly filled.

Related to this and probably stemming from the same function is the following problem.
**Example 2:**
```
<table>
  <tr><td>ROW 1 Single Cell</td></tr>
  <tr><td>ROW 2 Single Cell</td></tr>
</table>
```
In this case the demo shows two cells but only on one row. Like this...
<table><tr><td>ROW 1 Single Cell</td><td>ROW 2 Single Cell</td></tr></table>

**Comment by Aymkdn** [comment]
Thanks. I'll release a fix in a few minutes.

**Comment by Aymkdn** [comment]
v1.0.5 should have fixed this issue.

Thanks for letting me know!
