### ISSUE TITLE
Wrong url for pdfmake librairies

### ISSUE THREAD

**Issue by Etheonor** [Aymkdn/html-to-pdfmake#60]
Hi! Just to let you know the src for pdfmake and vfs_fonts lead to a 404. 

You need to update the Readme : 
<script src='https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/pdfmake.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/vfs_fonts.min.js'></script>

Cheers!

**Comment by Aymkdn** [comment]
Done. Thanks for the heads-up!
