### ISSUE TITLE
background color in span

### ISSUE THREAD

**Issue by jtasko** [Aymkdn/html-to-pdfmake#62]
Hi

I've got an html span element with the background color set to initial:
<span style="background-color: initial;">

This is results in a black background for the entire html content.

![image](https://user-images.githubusercontent.com/35415497/88141458-81bfdb00-cba8-11ea-9ef8-f3f553c1f3d9.png)

I want to override the 'initial' value to 'white' using the default style parameter for the htmlToPdfmake, but can't seem to do this for the span element. 

![image](https://user-images.githubusercontent.com/35415497/88141581-bd5aa500-cba8-11ea-8179-9bc7f97a7470.png)

Can you please recommend an approach?

Thanks

**Comment by Aymkdn** [comment]
You need to either manually set the style:
```html
<span style="background-color:white">Our Business</span>
```

Or [use a PDFMake class](https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#customize-style):
```js
var html = htmlToPdfmake(`<span class="bg-white">Our Business</span>`);
var docDefinition = {
  content: [
    html
  ],
  styles:{
    'bg-black':{
      background:'white'
    }
  }
};

var pdfDocGenerator = pdfMake.createPdf(docDefinition);
```

**Comment by jtasko** [comment]
Thanks for the quick response but I am still not able to get it to work.

Given this HTML code (which I have no control over):
`<span style="background-color: initial;">OUR BUSINESS</span>`

using the style :
```
{
    'bg-black':{
      background:'white'
    },
}
```
Still produces:
![image](https://user-images.githubusercontent.com/35415497/88207473-b2cdf900-cc04-11ea-98dc-02d3b33bfc7e.png)

I have tried other style overrides without success:

`    'html-span':{
      background:''
    },
    'html-span':{
      background:'white'
    },
`

I'm sure I'm missing something obvious!

Thanks
Jamie

**Comment by Aymkdn** [comment]
What about doing : 
```js
YourHTMLString = YourHTMLString.replace(/background-color:\s?initial/g, "background-color: white")
```

**Comment by jtasko** [comment]
that'll do it- thanks!
