### ISSUE TITLE
Multiple text decoration values are not inherited

### ISSUE THREAD

**Issue by kkolasinski** [Aymkdn/html-to-pdfmake#63]
When parsing an html string with multiple text decorations, only the last one is being applied to the child.

**Sample input:**
`<p><u><s>Test</s></u></p>`

**Expected Result:**
The "Test" text has both *strikethrough* and *underline* styles applied to it.

**Actual Result:**
Only the *strikethrough (lineThrough)* decoration is applied to the element.
```
[
  {
    "text": [
      {
        "text": [
          {
            "text": "Test",
            "nodeName": "S",
            "decoration": "lineThrough",
            "style": [
              "html-s",
              "html-u",
              "html-p"
            ]
          }
        ],
        "nodeName": "U",
        "decoration": "underline",
        "style": [
          "html-u",
          "html-p"
        ]
      }
    ],
    "nodeName": "P",
    "margin": [
      0,
      5,
      0,
      10
    ],
    "style": [
      "html-p"
    ]
  }
]
```

The PDFMake docs say that the `decoration` property should be a `string`, but `string[]` is also being parsed correctly and applies multiple decorations to an element.

I'm not sure if this is a PDFMake style inheritance issue or if this is something that could be fixed by traversing the elements tree and merging the `decoration` props into an array in html-to-pdfmake.

**Comment by Aymkdn** [comment]
That should be fixed with v2.0.9 👍
