### ISSUE TITLE
Allow adding new defaultStyles

### ISSUE THREAD

**Issue by sneu012** [Aymkdn/html-to-pdfmake#64]
First of all, thank you for the good work with the package.

I am trying to integrate this package to one of my projects in lieu of the the bits referenced from #205 from `pdfmake`.

I could not find all the tags that I want supported in the list of default styles. For example, the RTE I use uses `<del>` for strikethrough. 

I was able to resolve this by adding the new del tag with proper styles in the defaultStyles prop. It looks like you are not permitting new values to be added to the defaultStyles. I think it the project would be more extensible if we could add new tags/styles and just pass it via defaultStyles.

Something like this:

```
function changeDefaultStyles () {
    for (var keyStyle in options.defaultStyles) {
      // if the style is found- modify it. If not add a new style
      if (defaultStyles.hasOwnProperty(keyStyle)) {
        // if we want to remove a default style
        if (options.defaultStyles.hasOwnProperty(keyStyle) && !options.defaultStyles[keyStyle]) {
          delete defaultStyles[keyStyle];
        } else {
          for (var k in options.defaultStyles[keyStyle]) {
            // if we want to delete a specific property
            if (!options.defaultStyles[keyStyle][k]) delete defaultStyles[keyStyle][k];
            else defaultStyles[keyStyle][k] = options.defaultStyles[keyStyle][k];
          }
        }
      } else {
          // If a style is not found just add it to the list.
         defaultStyles[keyStyle] = options.defaultStyles[keyStyle]
      }
    }
  }
```

Let me know what you think.

**Comment by Aymkdn** [comment]
You can leverage the `html-del` style ([see doc](https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#customize-style)):
```js
var html = htmlToPdfmake(`<del>some stuff</del>`);

var docDefinition = {
 content: [
   html
 ],
 styles:{
   'html-del':{
     decoration:'lineThrough'
   }
 }
};

var pdfDocGenerator = pdfMake.createPdf(docDefinition);
```

**Comment by sneu012** [comment]
Yup, that works too!

But, would it also make sense to add the ability to expand defaultStyles?

**Comment by Aymkdn** [comment]
> But, would it also make sense to add the ability to expand defaultStyles?

I'm not sure… The purpose of `defaultStyles` is to apply a sort of browser's style to some basic elements, without having everyone to do it themselves (like links, bold, and so on).

I'll add `del` in the list of default styles in the next release, because it could benefit to everyone. And if some other styles are missing, I think it's better that people just submit a PR to add them.
