### ISSUE TITLE
convertToUnit(val) returns string for inputs without px/rem

### ISSUE THREAD

**Issue by MatthiasWerning** [Aymkdn/html-to-pdfmake#65]
Hello,

I've just noticed, that whenever the convertToUnit(val) function is called with an input without any scale unit (px or rem), it also returns back a string instead of a number.

This results in pdfmake crashing, since the resulting document definition contains a string value in a margin definition where a number should be placed (for example).

This should be easily fixable by parsing the val to a float before returning it in the first line of the convertToUnit(val) function.

**Comment by Aymkdn** [comment]
Do you have an example of a style that will cause this issue please?

**Comment by MatthiasWerning** [comment]
Consider this HTML snippet for example:

```
<ol>
   <li>List item</li>
</ol>
<div style="margin:0 0 0 23px">
   <span>2. First div</span>
</div>
<div style="margin:0 0 0 23px">
    <div>3. Second div</div>
</div>
```

Obviously this is not how a list should be declared (just from a semantic point of view), but this is for example a generated piece of HTML from an editor a lot of employees use at my company.

If you remove the quotation marks from the three "0" in the resulting json from this HTML snippet pdfmake seems to be outputting a pdf again.

**Comment by MatthiasWerning** [comment]
Strangely enough, if you drop the ordered list in the snippet, pdfmake does not longer crash, but instead prints an empty page. Seems like pdfmake isn't that much consistent when inserting strings instead of values that are required to be numbers.
