### ISSUE TITLE
For strange reasons, any link _a href_ tag in the web page converted to link with line break in PDF

### ISSUE THREAD

**Issue by devsherif** [Aymkdn/html-to-pdfmake#66]
I tested the same text on the online demo but the issue didn't happen. So it works well in the demo, but not on my NodeJs website.
Ex. <a href="someText">www.aWebSite.com</a> is a nice website
Will be printed in the exported pdf as:
someText
is a nice website

Can you help please ?

**Comment by Aymkdn** [comment]
Please, share your html code and the settings you use for PDFMake.

**Comment by devsherif** [comment]
It is just an extremely simple html:
<div>
  <h1>My Website</h1>
  <p>
To obtain a highly accurate assessment, scored by experts, along with personalized written feedback and professional coaching services, check out <a href='https://www.mywebsite.com'> My Website</a>.  You will find additional Background Information.
  </p>
</div>

And even more simple PDFMake settings:
const documentDefinition = {
      content: htmlToPdfMake(pdfContentString)
    };
    const self = this;
    pdfMake.createPdf(documentDefinition).getBase64(encodedString => {
      self.sendMail(firstName, userEmail, encodedString).subscribe(result => {
      });
    });

That's all.

**Comment by devsherif** [comment]
I found the issue and solved it. 
Adding a table then adding text with URL after that table causes the issue.
To fix it, just encapsulate that text with URL in <span> tag and everything will be formatted properly.

**Comment by Aymkdn** [comment]
Ok cool 👍🏻
