### ISSUE TITLE
white-space attribute in element tag <p> or <span>

### ISSUE THREAD

**Issue by MarioSergioLunaFilho** [Aymkdn/html-to-pdfmake#67]
Hi. 

The attribute "white-space" is suported to HTML tag 'p' or 'span' ? 

I tried use but it didn't work in PDF.

I need use "white-space=pre" attribute in one of this elements for don't lost format text of my v-textarea element

This is my first post, sorry anything.

![image](https://user-images.githubusercontent.com/30807979/91336265-0bfeee80-e7a8-11ea-8a80-b607f612d5a6.png)

**Comment by Aymkdn** [comment]
Did you try to add the class "whitespaceTexto" to the `span` itself?

I'm on vacation without a computer and it's hard to test on my phone.

**Comment by MarioSergioLunaFilho** [comment]
I try but it didn't work too. 

Using "preserveLeadingSpaces": true when finding a blank space the PDF understands it as a line break. What I really wanted, would be to keep the text format, as shown in the example on the HTML preview screen

**Comment by Aymkdn** [comment]
You'll have to dig into the PDFMake options/properties then...

**Comment by Aymkdn** [comment]
Basically you have to make it working with PDFMake and then share the solution with me. With that I can tell you how to use it in html-to-pdfmake

**Comment by MarioSergioLunaFilho** [comment]
I tried to use whiteSpace in many ways, but it didn't work. 

I will try to work around my problem in another way.

thanks for listening
