### ISSUE TITLE
Table border color is not working in defaultStyles

### ISSUE THREAD

**Issue by sandeepgoyal88** [Aymkdn/html-to-pdfmake#68]
defaultStyles: {
                        table: {
                            border: "1px solid #dddddd",
                        }
                    }
I'm trying to edit and set default border color for all the tables, but it isn't working. Hoping for the better solution. Thanks in advance.

**Comment by Aymkdn** [comment]
Hi,

You'll have to use a `tableLayout` to do it, as explained in the [PDFMake documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/tables/).

Example:

You first need to use `data-pdfmake` ([see documentation](https://github.com/Aymkdn/html-to-pdfmake#special-properties)) to define the name of your `layout`. Here I'll call it `customLayout`:
```html
<table data-pdfmake="{&quot;layout&quot;:&quot;customLayout&quot;}">
  <tr>
    <th>Header A</th>
    <th>Header B</td>
  </tr>
  <tr>
    <td>A1</td>
    <td>B1</td>
  </tr>
  <tr>
    <td>A2</td>
    <td>B2</td>
  </tr>
  <tr>
    <td>A3</td>
    <td>B3</td>
  </tr>
</table>
```

Next you need to define this layout as explained in the [PDFMake documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/tables/):
```js
var pdfDocGenerator = pdfMake.createPdf(docDefinition, {
  customLayout: {
    hLineColor: function (rowIndex, node, colIndex) {
      return rowIndex === 0 || rowIndex === node.table.body.length ? '#dddddd' : 'black';
    },
    vLineColor: function (colIndex, node, rowIndex) {
      return colIndex === 0 || colIndex === node.table.body[0].length ? '#dddddd' : 'black';
    }  
  }
});
```

And the result:
![image](https://user-images.githubusercontent.com/946315/92301909-e1f7ba00-ef67-11ea-8b1d-b6038e235ab8.png)

**Comment by sandeepgoyal88** [comment]
@Aymkdn Sorry for the late response was held up in something else
That is not my concern actually i read the entire documentation but my need is i've a editor which i'm using to format cotents
![image](https://user-images.githubusercontent.com/70775473/92745746-3f449e80-f3a0-11ea-9ffe-1e543578ee0a.png)

something like this so it returns a values which will be like

<table style=\"border-collapse: collapse; width: 100%; background-color: #dddddd; border-color: #dddddd; border-style: solid;\" border=\"1\">\n<tbody>\n<tr>\n<td style=\"width: 48.3413%;\">table header</td>\n<td style=\"width: 48.3413%;\">table header1</td>\n</tr>\n<tr>\n<td style=\"width: 48.3413%;\">column content</td>\n<td style=\"width: 48.3413%;\">column content</td>\n</tr>\n</tbody>\n</table>

though the border color set was set it returns default black borders

how can i handle this ? please help me out to resolve the issue .

**Comment by Aymkdn** [comment]
I explained everything in my comment. Please, refer to it.

You'll have to do some treatment on your HTML code before sending it to `html-to-pdfmake` / `PDFMake`.

**Comment by sandeepgoyal88** [comment]
my raw html code is working properly without any issue but when we do it through editor then it is not accepting the editor styles so atleast we need to set our default styles all the above treatments which u sent is not at all working

**Comment by Aymkdn** [comment]
Sorry to repeat myself, but you'll have to modify the html before sending it to this project. I don't say you have to change it in the editor, but to change it before passing it to html-to-pdfmake.

I'll close the issue as it's not related to this project anymore.
