### ISSUE TITLE
Table with rowspan and colspan

### ISSUE THREAD

**Issue by ekoeryanto** [Aymkdn/html-to-pdfmake#7]
Trying the online demo with table span not working

**Comment by Aymkdn** [comment]
Indeed, I just did a convertor for "simple HTML".

I currently don't have the time to work on implementing this feature. Feel free to do it and submit a pull request!

**Comment by jakubfindura** [comment]
I've recently found this same "issue" too. 

I am currently working on implementing it, the colspan at least. Since that's what I need in my use case.

**Comment by Aymkdn** [comment]
That should be resolved with v1.0.7

**Comment by ekoeryanto** [comment]
great, better with docs and demo

**Comment by Aymkdn** [comment]
You have the [`example.js`](https://github.com/Aymkdn/html-to-pdfmake/blob/master/example.js) where there is a table with colspan and rowspan, and the result in [`example.pdf`](https://github.com/Aymkdn/html-to-pdfmake/blob/master/example.pdf).

For the doc, everything is already explained in the [current doc](https://github.com/Aymkdn/html-to-pdfmake) and I don't think any additional information is required here!
