### ISSUE TITLE
Issue with text 

### ISSUE THREAD

**Issue by NigelRoth** [Aymkdn/html-to-pdfmake#70]
Uncaught SyntaxError: '' string literal contains an unescaped line break proc-html-pdf.asp:16:1298

I'm using classic asp and mysql database. I want to insert a longtext field but get the error above

<script>
    var val = htmlToPdfmake('<%= vFAQS("Answer") %>');
    var dd = {content:val};
    pdfMake.createPdf(dd).download();
</script>

The first 2 paras of the field are

 var val = htmlToPdfmake('<p>Whilst the UK is a nation of animal lovers, one cannot say that about Cyprus.&nbsp; The majority of Cypriots, both in the North and in the South, have a different attitude to animals.&nbsp; The subject of abandoned animals is a major problem here, and spaying/neutering is not a widespread practice.&nbsp; You will often find stray dogs being abandoned near your home, knowing that the ex-pats will take pity and often provide a home for them. If you find an abandoned animal and do not wish to &#39;adopt&#39; it, there is a charitable organisation - The Kyrenia Animal Rescue (KAR) that is staffed by volunteers that will do their best to try and find homes for animals. They do rely on charitable donations and have very limited resources, so cannot always help. &nbsp;Their contact number is 0533-xxx.&nbsp; Because of the volume of stray dogs KAR are limited in how many they can take. Puppies less than 6 months old will normally be accepted, otherwise if you find an abandoned dog you should contact your local Beledeysi. You must be made aware however that some authorities will simply have the animals put down. Details of this organisation can be found on <a href="http://www.kxxx.org" target="_blank">www.kxxx.org</a></p>

<p>For those of you that wish to bring your pets to the TRNC please visit the KAR website for up to date information.</p>
[....]

Can anyone help please?

**Comment by Aymkdn** [comment]
It's related a problem related to html-to-pdfmake… but it's a JavaScript / Coding issue.

You're passing a text with line breaks as a parameter of a function, which is not valid…

**Comment by NigelRoth** [comment]
Sorry forgive me if I'm not used to github but my post did have the  bracket p> bracket/p> html but was converted.
As far as I can see there are no line breaks, only html paras.

PS your code looks great if you can help me past this please

**Comment by Aymkdn** [comment]
You didn't put your code using the code tags of Github that made it very hard to read. I edited your post to display the code (see the [Github documentation](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks))

But it's still not clear what you pass to the function because I can still see line breaks in the code you provided:
```js
 var val = htmlToPdfmake('<p>Whilst the UK is a nation of animal lovers, one cannot say that about Cyprus.&nbsp; The majority of Cypriots, both in the North and in the South, have a different attitude to animals.&nbsp; The subject of abandoned animals is a major problem here, and spaying/neutering is not a widespread practice.&nbsp; You will often find stray dogs being abandoned near your home, knowing that the ex-pats will take pity and often provide a home for them. If you find an abandoned animal and do not wish to &#39;adopt&#39; it, there is a charitable organisation - The Kyrenia Animal Rescue (KAR) that is staffed by volunteers that will do their best to try and find homes for animals. They do rely on charitable donations and have very limited resources, so cannot always help. &nbsp;Their contact number is 0533-xxx.&nbsp; Because of the volume of stray dogs KAR are limited in how many they can take. Puppies less than 6 months old will normally be accepted, otherwise if you find an abandoned dog you should contact your local Beledeysi. You must be made aware however that some authorities will simply have the animals put down. Details of this organisation can be found on <a href="http://www.kxxx.org" target="_blank">www.kxxx.org</a></p>
// #### !!!! HERE THERE IS A LINE BREAK !!!!! ####
<p>For those of you that wish to bring your pets to the TRNC please visit the KAR website for up to date information.</p>
[....]
```

You should replace all line breaks by `<br>`. So instead of `<%= vFAQS("Answer") %>` you should have something like:
 `<%= Replace(vFAQS("Answer"), "\n", "<br>") %>`

I don't code with ASP so I don't know if this syntax is correct, but I guess you understand my point?

**Comment by Aymkdn** [comment]
Your error is very clear:
> string literal contains an **unescaped line break**

**Comment by NigelRoth** [comment]
Thanks for your patience. Your syntax is correct but there is no "\n" that I can see just close p and start p, in between which there seems to a blank line but no line break code I can find to replace.  So even with the replace function, still getting the line break error.
When I put the original text into your playground, it works perfectly, see screenshot.

![image](https://user-images.githubusercontent.com/36405728/94664681-da7fc280-0313-11eb-82d2-0f36cdc9ee53.png)

**Comment by NigelRoth** [comment]
OK, I've found it, I have to use 
Replace(vFAQS("Answer"), vbCrLf, "<br>" 
and now it works.
Many thanks, sorry if I was a bit slow this morning....
