### ISSUE TITLE
Problem with parsing `font`'s attributes

### ISSUE THREAD

**Issue by EOussama** [Aymkdn/html-to-pdfmake#72]
When there is an HTML 4 snippet that uses the `font` element, the parser should be able to preserve the color and font size that are usually passed in using the `color` and `size` attributes respectively.

At the moment, the following HTML 4 snippet will not be converted with the appropriate color and font size.

```html
<font color="#ffccee">colored text</font>
<font color="2">sized text</font>
```

**Comment by Aymkdn** [comment]
`font` is pretty old… HTML 4 as you said. I'll see if I add support for it, or not…

**Comment by EOussama** [comment]
> `font` is pretty old… HTML 4 as you said. I'll see if I add support for it, or not…

I know, I'm only asking for this because I noticed that most of the text editors still export in native HTML format as opposed to custom classes.

**Comment by AliMariam** [comment]
I need this aswell. I'm using [this package](https://www.npmjs.com/package/@kolkov/angular-editor) that exports in HTML 4 format. I'm having a hard time conserving colors and text sizes.

**Comment by Aymkdn** [comment]
OK. I'll see what I can do. Please, except some delay.

**Comment by Aymkdn** [comment]
Added in v2.1.0
