### ISSUE TITLE
Text is breaking bad.

### ISSUE THREAD

**Issue by erald14** [Aymkdn/html-to-pdfmake#74]
<img width="374" alt="Screenshot 2020-10-06 at 5 16 16 PM" src="https://user-images.githubusercontent.com/44317405/95221356-a61a7380-07f7-11eb-864a-88c5f26ef891.png">
this is the top of the page. The sentence is started in previous page and only one word on second page. Any way to prevent that?

**Comment by Aymkdn** [comment]
I don't know any magical way to do it.

You can have a look at the [PDFMake documentation](https://pdfmake.github.io/docs/0.1/). For example you could change the [page's margins](https://pdfmake.github.io/docs/0.1/document-definition-object/page/).
