### ISSUE TITLE
Problem with font-family

### ISSUE THREAD

**Issue by antoniolucasnobar** [Aymkdn/html-to-pdfmake#76]
Hi, 

Congrats on your project. I am trying to use it and having problems with font-family.

I try to use this HTML: `<p style="font-family:'Courier New', Courier, monospace;">My title</p>`
I try this in your demo page: https://aymkdn.github.io/html-to-pdfmake/index.html

Here is the outuput:

```json
var dd = {
  "content": [
    {
      "text": "My title",
      "nodeName": "P",
      "margin": [
        0,
        5,
        0,
        10
      ],
      "font": "courier new', courier, monospace",
      "style": [
        "html-p"
      ]
    }
  ],
}
```
As you can see, there is a problem with the font field: `"font": "courier new', courier, monospace",`

courier new is missing its starting single quote. But even when I manually add the quote, I am not able to generate PDF in pdfmake playground: http://pdfmake.org/playground.html

It complains with this message: 
```
Error: Font ''courier new', courier, monospace' in style 'normal' is not defined in the font section of the document definition.
```
this time, there are two single quotes in the error console msg.

Well, I think there is a problem with the translation where we lose the first single quote.

Besides that, I think that pdfmake will not understand several fonts, so, maybe this translator should pick only the first? 

If you can help, Can I generate a PDF without providing fonts? Not every PDF has fonts embebed. Or is it impossible with pdfmake? It looks like, as I saw in their docs: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/

**Comment by Aymkdn** [comment]
I'll check tomorrow how PDFMake handles the fonts and I'll fix it if there is a solution there.

**Comment by antoniolucasnobar** [comment]
thanks for so quick response

**Comment by Aymkdn** [comment]
Using Fonts in PDFMake is not basic… it looks like that only one font can be used any way.

The thing I changed:
  - it strips all the fonts, but the first one;
  - it removes any `'` and `"`;
  - it rename the font using the same syntax that are usually associated with fonts in PDFMake, e.g. `courier new` will be renamed to `CourierNew` – I don't know if it's the right way to do it… I'm opened to suggestion.

So a `style="font:'courier new', courier, monospace"` will return `font:"CourierNew"`.

**Comment by Aymkdn** [comment]
v2.1.1 published

Thanks
