### ISSUE TITLE
limit image size?

### ISSUE THREAD

**Issue by antoniolucasnobar** [Aymkdn/html-to-pdfmake#77]
Hi, is there a way to globally limit image size? My app lets the users insert images in any size in the ckeditor. I get ckeditor HTML and try to generate PDF, but some images get cropped.

thanks in advance.

**Comment by Aymkdn** [comment]
You'll need to check the PDFMake documentation for that.

**Comment by antoniolucasnobar** [comment]
thank you for your quick response. I looked at PDFMake docs: https://pdfmake.github.io/docs/0.1/document-definition-object/images/

it says that the definition should be made at the object level:
```javascript
{
      // if you specify width, image will scale proportionally
      image: 'data:image/jpeg;base64,...encodedContent...',
      width: 150
    },
```
I could not find any global configuration to limit the max size of all images. 

I tried to define `html-image` and `html-figure` configurations:
```
    const docDefinition = {
        content: html,
        defaultStyle: {
            font: 'Courier'
        },
        styles:{
            'html-image':{ maxWidth: 200, _maxWidth: 200 },
            'html-figure':{ maxWidth: 200, _maxWidth: 200 },
        }
    };
```
but it did not worked. 

I use output of ckeditor,  so users can add images of variable sizes. 

IMO, pdfmake should resize images automatically to fit paper size, but, it is not the case.

I saw html-to-pdf defines:

```
​​_maxWidth: 670
​​_minWidth: 670
nodeName: "FIGURE"
```
 so I thought it was possible to overwrite some styling here in html-to-pdf. I tried: 
```js
    const html = htmlToPdfmake( editorData, {
        defaultStyles: {
            img: { maxWidth: 200, _maxWidth: 200},
            figure: { maxWidth: 200, _maxWidth: 200}
        }
    } );
```
but it did not worked. Is there any other parameter I could use?

**Comment by antoniolucasnobar** [comment]
I noted if I edit the `defaultStyles` to add `img` and `figure` entries, I can customize (as described above):
```
  // set default styles
  var defaultStyles = {
//...
    img: {},
    figure: {}
}
```

Is there another way to customize `img` and `figure` tags?
Or maybe we could change the `function changeDefaultStyles ()` to accept new items, when the user specify them like I did before.

**Comment by Aymkdn** [comment]
The below should work:
```js
var docDefinition = {
  content: [
    html
  ],
  styles:{
    'html-img':{
      maxWidth:'200px'
    }
  }
}
```

However it does seem to work very well in various cases. I imagine it's a PDFMake bug…

Putting the `max-width` in the `style` seems to work too, but it's probably not good for your case. So, OK, I've added the possibility to add new `defaultStyles` as suggested.

**Comment by Aymkdn** [comment]
v2.1.1 published

Thanks

**Comment by DocBouCou** [comment]
> The below should work:
> 
> ```js
> var docDefinition = {
>   content: [
>     html
>   ],
>   styles:{
>     'html-img':{
>       maxWidth:'200px'
>     }
>   }
> }
> ```
> 
> However it does seem to work very well in various cases. I imagine it's a PDFMake bug…
> 
> Putting the `max-width` in the `style` seems to work too, but it's probably not good for your case. So, OK, I've added the possibility to add new `defaultStyles` as suggested.

I suggest that you may add this example in the docs :)

**Comment by Aymkdn** [comment]
The documentation already provides all the information. Otherwise there is the closed issues for specific cases ;-)
