### ISSUE TITLE
Support for new style attributes: margin-left, text-indent

### ISSUE THREAD

**Issue by antoniolucasnobar** [Aymkdn/html-to-pdfmake#78]
Hey,

do you plan to give a better support these attributes?
- margin-left
- text-indent

Ex.: 
```html
<p style="margin-left:8cm;text-indent:3cm;">Nullam varius nunc vitae urna vestibulum euismod. Donec venenatis quis sem aliquam sodales. Morbi volutpat vel neque</p>
```
generates:
```json
var dd = {
  "content": [
    {
      "text": "Nullam varius nunc vitae urna vestibulum euismod. Donec venenatis quis sem aliquam sodales. Morbi volutpat vel neque",
      "nodeName": "P",
      "margin": [
        0,
        5,
        0,
        10
      ],
      "marginLeft": "8cm",
      "textIndent": "3cm",
      "style": [
        "html-p"
      ]
    }
  ],
  "styles": {}
}
```

It adds the attributes as Strings, and add an automatic margin array. This way, neither of them work. I used the pdfmake playground

I changed the marginLeft to a number and it did not change anything. Only when I removed the margin array it worked as expected.

The textIndent did not work at all. I tried the same as described above. I suppose maybe the problem is with pdfmake. If you know how to make it work, please let me know.

I ask if it is possible:
- not to add the margin array when marginLeft is defined
- convert the cm to a number (as pdfmake expects)

if you only remove the margin array, pdfmake gives an error:
`Uncaught (in promise) Error: unsupported number: 408cm00`

thanks in advance.

EDIT: I was able to remove the margin array using the options object, as stated in the docs, but I think would be nice if the framework could detect. But I do not know if it is possible.

I sent a PR to add conversion cm => pt

**Comment by antoniolucasnobar** [comment]
I checked the pdfmake code and they use `leadingIndent` instead of `textIndent`

If I change manually the attribute name, it works on pdfmake.

Is it possible to replace the name of the attribute? I am checking the code, but I still do not understand it enough.

thanks in advance

**Comment by Aymkdn** [comment]
I'll realease it in a few minutes. Just checking your other opened issues first.

Thanks for sharing!
