### ISSUE TITLE
Question: is it possible to remove font attribute of all nodes?

### ISSUE THREAD

**Issue by antoniolucasnobar** [Aymkdn/html-to-pdfmake#82]
As pdfmake requires any fonts to be embedded, I would like to remove all fonts unmapped.

Ex.: I mapped only Courier New and Times New Roman. 
```js
    const fonts = {
        CourierNew: {
            normal: 'courier-new.ttf',
            bold: 'courier-new-grassetto.ttf',
            italics: 'courier-new-corsivo.ttf',
            bolditalics: 'courier-new-grassetto-corsivo.ttf'
        },
        TimesNewRoman: {
            normal: 'times-new-roman.ttf',
            bold: 'times-new-roman-grassetto.ttf',
            italics: 'times-new-roman-corsivo.ttf',
            bolditalics: 'times-new-roman-grassetto-corsivo.ttf'
        }
    };
```
If the user puts some text with Arial, I would like to remove this reference to Arial as it will cause error in the app.

I tried to loop over html array:

```js
    const html = htmlToPdfmake( editorData);
    html.forEach(item => { 
        if (item.font && fonts[item.font] === undefined) {
             delete item.font;
        }
});
```

But, Not always the font is in the top level. For instance, if I have a paragraph inside a blockquote, the font attribute is inside the stack attribute of the blockquote (I wonder how many nested levels can exist).

Is there a deterministic way to remove all the font that are not mapped in my application?

**Comment by Aymkdn** [comment]
I would recommend to do it BEFORE passing the data to `htmlToPdfmake`. So in your `editorData` to replace "arial" with whatever font you'd like to use.

The other option is to go through all the levels, like here: https://stackoverflow.com/questions/30128834/deep-changing-values-in-a-javascript-object to remove the font attribute if needed.

**Comment by antoniolucasnobar** [comment]
Thank you! I will check it out!
