### ISSUE TITLE
Uncaught typeerror : cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by madhusudhanv255** [Aymkdn/html-to-pdfmake#83]
<img width="1214" alt="Screenshot 2020-11-11 at 10 00 57 AM" src="https://user-images.githubusercontent.com/12857175/98766050-f8f1d700-2404-11eb-811d-8dad46d7a41d.png">

I am using  htmltopdfmake 2.1.0  version

**Comment by Aymkdn** [comment]
Please, provide the html code that you pass.

**Comment by madhusudhanv255** [comment]
This is the html code i am passing

<table class="alertMessageTable" width="100%">
<tbody>
<tr>
<td class="TypicalText"><br /><br />
<div class="alertMessageBodyContent"><br /><br />
<div id="ctl00_ContentPlaceHolder1_workArea1_alertsControl_ctl00_AlertMessageBody"><br /><br />
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="TypicalText" rowspan="100" valign="top" width="80"><strong>Comment:</strong></td>
</tr>
<tr>
<td><span class="regular">You are receiving this alert because Schwab's fraud monitoring systems recently detected evidence that someone may have obtained the username and password(s) of your client(s) from a non-Schwab account or website and tried them successfully on SchwabAlliance.com. This type of login attempt is made possible when your client(s) uses the same username and password on multiple sites.</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">We recommend you and your client closely review all accounts accessed through SchwabAlliance.com and let us know immediately if you see any suspicious or unrecognized activity. We also encourage your client to monitor all their financial accounts and to change their passwords on other sites they access.</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">To protect your client(s)' confidential information, we restricted their online account access and we have been monitoring the account(s) for suspicious activity. To remove the block from their web access, they will need to contact our Identify Theft Team at 877-903-1570. Your client will be required to change their Schwab Login ID and Password. Your client should run a full virus scan on their computer prior to contacting the Identity Theft Team.</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">We will also send a communication to your client, advising them of the issue. A copy of the communication that will be mailed to your client(s) can be found at the following URL:</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">advisorservices-pce.schwab.com/credentialclientcorrespondence</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">Please copy and paste it into another browser.</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">The security of your client(s)' accounts is important to us. If you would like additional information to assist you with talking with your client(s) about this incident, please contact your Relationship Manager or service team.</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><span class="regular">The impacted clients are listed below:</span></td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><br /><br />
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td bgcolor="BEBEBE"><br /><br />
<table border="1" cellspacing="1" cellpadding="5">
<tbody>
<tr class="alertsDetailTypicalTextBold">
<td>Account ID</td>
<td>Account Type</td>
<td>Account Registration</td>
</tr>
<tr>
<td class="regular">78776764</td>
<td class="regular">IRA</td>
<td class="regular">MICHAEL RUTILA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td colspan="100"></td>
</tr>
<tr>
<td><br /><br />
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td class="TypicalText" rowspan="100" valign="top" width="100">(1016-NN7S)</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</td>
</tr>
</tbody>
</table>

**Comment by Aymkdn** [comment]
Your HTML code doesn't make sense and it makes it super complicated to deal with.

To do something like: 
<table border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td class="TypicalText" rowspan="2" valign="top" width="80"><strong>Comment:</strong></td>
      <td><span class="regular">You are receiving this alert because Schwab's fraud monitoring systems recently detected evidence that someone may have obtained the username and password(s) of your client(s) from a non-Schwab account or website and tried them successfully on SchwabAlliance.com. This type of login attempt is made possible when your client(s) uses the same username and password on multiple sites.</span></td>
    </tr>
    <tr>
      <td>Some other text</td>
    </tr>
  </tbody>
</table>

The HTML should look like that:
```html
<table border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
       <!-- you should have 2 `<td>` here and the `rowspan` should reflect the real number of rows -->
       <!-- in your code you only have 1 `<td>` and `100` for the `rowspan` -->
      <td class="TypicalText" rowspan="2" valign="top" width="80"><strong>Comment:</strong></td>
      <td><span class="regular">You are receiving this alert because Schwab's fraud monitoring systems recently detected evidence that someone may have obtained the username and password(s) of your client(s) from a non-Schwab account or website and tried them successfully on SchwabAlliance.com. This type of login attempt is made possible when your client(s) uses the same username and password on multiple sites.</span></td>
    </tr>
    <tr>
       <!-- you should have one `<td>` here, and no `colspan` -->
       <!-- in your code you have `100` for the `colspan` when it should be none, or `1` -->
      <td>Some other text</td>
    </tr>
  </tbody>
</table>
```

It's already difficult to interpret the valid HTML code to transform it to PDF, so I don't support the invalid or too complicated one.

The purpose of this lib is to deal with correct HTML code. So I invite you to simplify your HTML code or find another solution.

**Comment by madhusudhanv255** [comment]
I apologise for the format i pasted. Does htmltopdfmake support the following html?
<table class="alertMessageTable" width="100%">
    <tbody>
        <tr>
            <td class="TypicalText"><br /><br />
                <div class="alertMessageBodyContent"><br /><br />
                    <div id="ctl00_ContentPlaceHolder1_workArea1_alertsControl_ctl00_AlertMessageBody"><br /><br />
                        <table border="0" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr>
                                    <td class="TypicalText" rowspan="100" valign="top" width="80">
                                        <strong>Comment:</strong></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">You are receiving this alert because Schwab's fraud
                                            monitoring systems recently detected evidence that someone may have obtained
                                            the username and password(s) of your client(s) from a non-Schwab account or
                                            website and tried them successfully on SchwabAlliance.com. This type of
                                            login attempt is made possible when your client(s) uses the same username
                                            and password on multiple sites.</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">We recommend you and your client closely review all
                                            accounts accessed through SchwabAlliance.com and let us know immediately if
                                            you see any suspicious or unrecognized activity. We also encourage your
                                            client to monitor all their financial accounts and to change their passwords
                                            on other sites they access.</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">To protect your client(s)' confidential information, we
                                            restricted their online account access and we have been monitoring the
                                            account(s) for suspicious activity. To remove the block from their web
                                            access, they will need to contact our Identify Theft Team at 877-903-1570.
                                            Your client will be required to change their Schwab Login ID and Password.
                                            Your client should run a full virus scan on their computer prior to
                                            contacting the Identity Theft Team.</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">We will also send a communication to your client, advising
                                            them of the issue. A copy of the communication that will be mailed to your
                                            client(s) can be found at the following URL:</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span
                                            class="regular">advisorservices-pce.schwab.com/credentialclientcorrespondence</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">Please copy and paste it into another browser.</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">The security of your client(s)' accounts is important to
                                            us. If you would like additional information to assist you with talking with
                                            your client(s) about this incident, please contact your Relationship Manager
                                            or service team.</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><span class="regular">The impacted clients are listed below:</span></td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><br /><br />
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td bgcolor="BEBEBE"><br /><br />
                                                        <table border="1" cellspacing="1" cellpadding="5">
                                                            <tbody>
                                                                <tr class="alertsDetailTypicalTextBold">
                                                                    <td>Account ID</td>
                                                                    <td>Account Type</td>
                                                                    <td>Account Registration</td>
                                                                </tr>
                                                                <tr>
                                                                    <td class="regular">78776764</td>
                                                                    <td class="regular">IRA</td>
                                                                    <td class="regular">MICHAEL RUTILA</td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="100"></td>
                                </tr>
                                <tr>
                                    <td><br /><br />
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td class="TypicalText" rowspan="100" valign="top" width="100">
                                                        (1016-NN7S)</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>

**Comment by Aymkdn** [comment]
[Yes, as documented](https://github.com/Aymkdn/html-to-pdfmake#html-tags-supported). However `html-to-pdfmake` is just a first step, then everything is sent to PDFMake, and you'll have to check [their documentation about images](https://pdfmake.github.io/docs/0.1/document-definition-object/images/).
