### ISSUE TITLE
data-pdfmake custom layout functions do not run

### ISSUE THREAD

**Issue by giosifelis** [Aymkdn/html-to-pdfmake#84]
Hello,

is there a way to use data-pdfmake with a layout function?  i've tried this 

``` <table data-pdfmake="{&quot;layout&quot;: {&quot;hLineWidth&quot;:function(i,node){return .5;}}">```

but it does not work. (it works with the predefined layouts from pdfmake)

I am trying to have a custom layout
```layout: { hLineWidth : function(i,node) {return .5; } }```

**Comment by Aymkdn** [comment]
No, you cannot use a function there. You have to define the function in the parameters of pdfmake.

See https://github.com/Aymkdn/html-to-pdfmake/blob/8fdf94a8a679dcfb803ec822a22b1f91154b1474/example.js#L268
