### ISSUE TITLE
suggestion:  replace HR parsing from canvas to svg

### ISSUE THREAD

**Issue by giosifelis** [Aymkdn/html-to-pdfmake#85]
Hello, 
The canvas that is been used for the `<hr>` created extra lines on the pdf (I cannot figure out know why).

To solve it I commented this: 

```ts
ret.canvas = [
     {
                 type: styleHR.type,
                 x1: styleHR.left,
                 y1: 0,
                 x2: styleHR.width,
                 y2: 0,
                 lineWidth: styleHR.thickness,
                 lineColor: styleHR.color
     }
];
```

and added this in its place: 

```ts 
  ret.svg = `<svg height="1" width="500"><line x1="0" y1="0" x2="514" y2="0" stroke="black" stroke-width="1" stroke-linecap="butt"/></svg>`
```

This is based on the pdf documentation

https://pdfmake.github.io/docs/0.1/document-definition-object/svgs/

**Comment by Aymkdn** [comment]
OK, let me look at it during the week-end as I'm quite busy today.

Thanks.

**Comment by Aymkdn** [comment]
Without an example I cannot really see your problem.

You said:
> the `<hr>` created extra lines

I cannot reproduce it. However there are bottom and top margins for `<hr>`, so maybe it's what you mean by "extra lines"?

You can overwrite the margins by using the below code:
```html
<hr data-pdfmake="{&quot;margin&quot;:[0,0,0,0]}">
```
