### ISSUE TITLE
possible to replace NON-BREAKING HYPHEN to \u2011

### ISSUE THREAD

**Issue by zulander1** [Aymkdn/html-to-pdfmake#86]
Is there a way to replace the hyphen with with non breaking hyphen, it is causing the a space in the pdf.

When i replace directly with the string it works but when I  preprocess the content and replace it before using htmlToPdfmake it has no effect

Thanks

```
    replaceText(selector) {
        $(selector).each(function () {
            var $this = $(this);
            if (!$this.children().length) {
                let newVal = new Array($this.text().length);
                let val = $this.text();
                for (var z = 0; z < val.length; z++) {
                    let c = val[z];
                    if (val[z] == '-') {
                        c = '\u2011';
                    }
                    newVal[z] = c;

                }
                $this.text(newVal.join(''));
            }
        });
        return jQuery('<div />').append(selector).html();
    }

        let htmlContent = htmlToPdfmake(replaceText(content), {
            defaultStyles: { // change the default styles
                p: '',
                h1: '',
                h2: '',
                h3: '',
                a: '',
                li: '' // remove all default styles for <LI>
            }
        });

```

```
 let someValue="Lorem Ipsum is simply d-ummy text of th-e printing and typese-tting industry. Lorem Ipsum has b-een the industry's standard dummy text ever since the 1500s"
 let someValue1="Lorem Ipsum is simply d-ummy text of th-e printing and typese-tting industry. Lorem Ipsum has b-een the industry's standard dummy text ever since the 1500s"
 
//replace char

  let val = someValue;
    let newVal = new Array(val.length);
                for (var z = 0; z < val.length; z++) {
                    let c = val[z];
                    if (val[z] == '-') {
                        c = '\u2011';
                    }
                    newVal[z] = c;

                }
    someValue=newVal.join('');

 
 var dd = {
	"pageSize": {
		"width": 81.4968,
		"height": "auto"
	},
	"defaultStyle": {
		"fontSize": "7"
	},
	"pageMargins": [
		0,
		0,
		0,
		0
	],
	"content": [
		{
			"table": {
				"body": [
					[
						{
							"fillColor": "",
							"columns": [
								[
									{
										"text": someValue,
										"nodeName": "P",
										"alignment": "justify",
										"style": [
											"html-p"
										]
									}
								]
							]
						}
					]
				] 
			},
 
		}
	]
}
```

**Comment by Aymkdn** [comment]
I tried the below and it worked:
```js
var html = htmlToPdfMake(`<p>Lorem Ipsum is simply d-ummy text of th-e printing and typese-tting industry. Lorem Ipsum has b-een the industry's standard dummy text ever since the 1500s</p>`.replace(/-/g, "\u2011"));
```

**Comment by zulander1** [comment]
the style has to be text-align: justify

 <```
html>
<head>
</head>
<body><iframe id="pdfV"></iframe></body>

  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/pdfmake@latest/build/pdfmake.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/pdfmake@latest/build/vfs_fonts.js"></script>
  <script>
    function  replaceText(selector) {
        $(selector).each(function () {
            var $this = $(this);
            if (!$this.children().length) {
                 let val = $this.text().replace(/-/g, "\u2011");
 
                $this.text(val);
            }
        });
        return jQuery('<div />').append(selector).html();
    }
  let htmlContent = htmlToPdfmake(replaceText("<p style='text-align: justify;'>Lorem Ipsum is simply d-ummy text of th-e printing and typese-tting industry. Lorem Ipsum has b-een the industry's standard dummy text ever since the 1500s</p>"), {
    defaultStyles: { }
});
 

var dd = {
    pageSize: {
        width: 1.1319 * 72,
        height: 'auto'
    },
    defaultStyle: {
        fontSize: '7'
    },
    pageMargins: [0, 0, 0, 0],
    content: [{
        table: {
            body: [
                [{

                    columns: [htmlContent],
                }]
            ],
        }

    }]
};
pdfMake.createPdf(dd).getDataUrl(function(outDoc) {
    document.getElementById('pdfV').src = outDoc;
});
</script>
</html>
```

**Comment by Aymkdn** [comment]
I added a `replaceText` option that should resolve your issue.

See the documentation: https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#replacetext
