### ISSUE TITLE
Problem with what looks like a new version

### ISSUE THREAD

**Issue by NigelRoth** [Aymkdn/html-to-pdfmake#87]
I have made no changes to the code my end, but as of today, there is what looks like a bug and it seems you have put up a new version yesterday. Is there somewhere to download the previous version please?

The error is

Uncaught TypeError: options is undefined
    parseElement https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    parseElement https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    parseElement https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    convertHtml https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    exports https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    <anonymous> https://brstrnc.com/proc/proc-html-pdf.asp?p=news&news=342&d=342.pdf:46
browser.js:1:2961
    parseElement https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    parseElement https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    forEach self-hosted:206
    parseElement https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    convertHtml https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    exports https://cdn.jsdelivr.net/npm/html-to-pdfmake@latest/browser.js:1
    <anonymous> https://brstrnc.com/proc/proc-html-pdf.asp?p=news&news=342&d=342.pdf:46

**Comment by Aymkdn** [comment]
Thanks for letting me know.

I've just published a new version (it should be available in a few minutes to the CDN).
