### ISSUE TITLE
It do not work on pdfmake server side

### ISSUE THREAD

**Issue by aaknai** [Aymkdn/html-to-pdfmake#88]
when I tryied to use this lib for server side version of pdfmake it raises error that window do not exists.
```javascript

import htmlToPdfmake from "html-to-pdfmake";
const partialPdf = htmlToPdfmake(html);
```
![image](https://user-images.githubusercontent.com/6787216/106786614-08bd3800-664f-11eb-9280-fd3dccb17845.png)

This is a clear sign that is was not designed to work with pdfmake on the server side.

Taking a short look at the code I realized that the window object can be passed in options and the only thing it's going use it for is to take a reference of DOMParser.

a way to have a DOMParser on node server is throw another dependency "xmldom"
```javascript

import htmlToPdfmake from "html-to-pdfmake";
import {DOMParser} from "xmldom";
// or
// const DOMParser = require("xmldom").DOMParser;
//....
const partialPdf = htmlToPdfmake(html,{
  window:{
    DOMParser
  }
});
```
So far, so good but I faced another problem:
![image](https://user-images.githubusercontent.com/6787216/106788132-d9a7c600-6650-11eb-997b-4d585ec94076.png)

The issue is in the code side of this library in a function called convertHtml

```javascript
var convertHtml = function(htmlText) {
    // Create a HTML DOM tree out of html string
    var parser = new wndw.DOMParser();
    var parsedHtml = parser.parseFromString(htmlText, 'text/html');

    var docDef = parseElement(parsedHtml.body, []);
    // remove first level
    return  docDef.stack || docDef.text;
  }
```
my solution is to add parsedHtml.firstChild as alternative to parsedHtml.body
```javascript
var convertHtml = function(htmlText) {
    // Create a HTML DOM tree out of html string
    var parser = new wndw.DOMParser();
    var parsedHtml = parser.parseFromString(htmlText, 'text/html');

    var docDef = parseElement(parsedHtml.body || parsedHtml.firstChild, []);
    // remove first level
    return  docDef.stack || docDef.text;
  }
```
Moreover in my case the html isapartal one that consists of two div elements... in that case only the first one will be converted, to avoid that issue i wrapped my html in a body element

ASAP I will do a PR for this so others can benefit from this lib on server side

**Comment by aaknai** [comment]
Nevermind, now I saw the documentation on the bottom about the usage of jsdom.
You can close this and sorry to bothering you with this no issue

**Comment by Aymkdn** [comment]
Please, check the documentation: https://github.com/Aymkdn/html-to-pdfmake#window
