### ISSUE TITLE
How to pass data to html code ? 

### ISSUE THREAD

**Issue by ziiko10** [Aymkdn/html-to-pdfmake#89]

**Comment by Aymkdn** [comment]
Please, read the documentation, or provide a description to your issue.

**Comment by ziiko10** [comment]
I want to pass dynamic data to htmlToPdfmake function in order to print the PDF with dynamic datas like this : 

       var users = this.users;
       var html = htmlToPdfmake(`
        <div>
          <h1>My title</h1>
           users.forEach(user => {
            <p>{{user.name}}</p>
           })
        </div>
      `);

**Comment by Aymkdn** [comment]
You have to generate the HTML you want using the dynamic data, and then pass the generated HTML to `html-to-pdfmake`. It's not the job of this library to manage your dynamic HTML.
