### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by Sun3** [Aymkdn/html-to-pdfmake#92]
I installed html-to-pdfmake with ```npm install html-to-pdfmake``` for a Vue 3 and Typescript application but it does not seem to be compatible. When I try to import ```import htmlToPdfmake from "html-to-pdfmake"'``` you get an error ```Could not find a declaration file for module 'html-to-pdfmake'```

I also tried ```npm i --save-dev @types/html-to-pdfmake``` but that did not work, lot's of errors.

Any suggestions?
Thank you.

**Comment by Aymkdn** [comment]
What about using `require` instead of `import` if your configuration doesn't support it? 
```js
var htmlToPdfmake = require("html-to-pdfmake");
```

**Comment by Sun3** [comment]
Yes, I did try it but I receive the error: 

```
This dependency was not found

* pdfmake/build/pdfmake in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/Home.vue?vue&type=script&lang=ts
```

The following is my code:

```
      const pdfMake = require("pdfmake/build/pdfmake");
      const htmlToPdfmake = require("html-to-pdfmake");

      const html = htmlToPdfmake(`
        <div>
          <h1>My title</h1>
          <p>
            This is a sentence with a <strong>bold word</strong>, <em>one in italic</em>,
            and <u>one with underline</u>. And finally <a href="https://www.somewhere.com">a link</a>.
          </p>
        </div>
      `);
      
      await html.createPDF()
```

**Comment by Aymkdn** [comment]
Did you install pdfmake?

**Comment by Sun3** [comment]
Yes, I have installed pdfMake but it also is not recognized when I import it in Vue 3 using Typescript as per pdfMake documentation.

```
import * as pdfMake from "pdfmake/build/pdfmake";
```

Similar error:
```
ERROR in src/views/Home.vue:17:27
TS7016: Could not find a declaration file for module 'html-to-pdfmake'. 'C:/Users/marco/Downloads/Vue3/htmlto-pdfmake/node_modules/html-to-pdfmake/index.js' implicitly has an 'any' type.
  Try `npm install @types/html-to-pdfmake` if it exists or add a new declaration (.d.ts) file containing `declare module 'html-to-pdfmake';`
```

Not really sure why...
Thanks.

**Comment by Aymkdn** [comment]
Sorry I don't know. I don't use Vue 3 or TypeScript.

I'll close this issue because I cannot help. If you find what is wrong, feel free to share here.

**Comment by Sun3** [comment]
I closed my editor and came back in and it's now recognizing the ```import * as pdfMake from "pdfmake/build/pdfmake";```

Unfortunately still the same issue with ```import * as htmlToPdfmake from 'html-to-pdfmake'``` or ```import htmlToPdfmake from 'html-to-pdfmake'```

I understand what you are saying and thank you. If I find a solution I will post it.

**Comment by Sun3** [comment]
I got it working with the following:

Create a file called ```typing.d.ts```

File Content:
```
declare module 'html-to-pdfmake.js';
```

I hope this helps anyone that is using Vue 3 and Typescript.

**Comment by Aymkdn** [comment]
Thanks for sharing!
