### ISSUE TITLE
Change page orientation

### ISSUE THREAD

**Issue by perervar** [Aymkdn/html-to-pdfmake#95]
Thanks for your development. 
Please tell me if it is possible to somehow add a change in the page orientation? (pageOrientation: 'landscape'). 

So that you can add something like pdf-orientation-landscape in the HTML code, as it is implemented with pdf-pagebreak-before.

**Comment by Aymkdn** [comment]
It's a [PDFMake option](https://pdfmake.github.io/docs/0.1/document-definition-object/page/) that you have to define by yourself:
```js
var docDefinition = {
  content: [
    htmlGeneratedWithHTMLtoPDFMake // this is the part that my lib is doing
  ],
  pageOrientation: 'landscape' // this is the option you defined that has nothing to do with html-to-pdfmake
}
```

If you need it to be defined in your HTML code, you could define some CSS attributes and use JavaScript to find it.

If I didn't understand your question, then please provide more details/examples/explanations in this thread.

**Comment by perervar** [comment]
I would like to be able to determine the orientation of the new page when the page breaks, something like the example below. Is it possible to implement this using html-to-pdfmake?

The thing is, I am using html-to-pdfmake to load custom HTML templates. Users who upload templates for PDF creation do not have access to edit the js file. Those. it is necessary to be able to add page orientation directly to html-to-pdfmake

```
var html = htmlToPdfmake(`
  <div>
    <h1>My title on page 1</h1>
    <p>
      This is my paragraph on page 1.
    </p>
    <h1 class="pdf-pagebreak-before pdf-landscape">My title on page 2</h1>
    <p>This is my paragraph on page 2.</p>
  </div>
`);
```

**Comment by Aymkdn** [comment]
Ah OK, I think I understand now. I think it's doable. I'll try to find some time later today to add it.

**Comment by Aymkdn** [comment]
You can already do it, using the [special properties](https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#special-properties) called `data-pdfmake`:
```html
<div>
  <h1>My title</h1>
  <p>
    This is a sentence with a <strong>bold word</strong>, <em>one in italic</em>,
    and <u>one with underline</u>. And finally <a href="https://www.somewhere.com">a link</a>.
  </p>
  <div class="pdf-pagebreak-before" data-pdfmake="{&quot;pageOrientation&quot;:&quot;landscape&quot;}">page break here</div>
</div>
```

And in your JS:
```js
var docDefinition = {
  content: [
    html // created with html-to-pdfmake
  ],
  pageBreakBefore: function(currentNode) {
    return currentNode.style && currentNode.style.indexOf('pdf-pagebreak-before') > -1;
  }
}
```
