### ISSUE TITLE
Problem with white-space

### ISSUE THREAD

**Issue by benvasseur** [Aymkdn/html-to-pdfmake#96]
Hi,

I'm trying to convert a div with white-space but the pdf put everything on one line. I'm not sure what is the problem here.

![Screen Shot 2021-03-29 at 9 45 08 AM](https://user-images.githubusercontent.com/46235560/112774743-890f8080-9075-11eb-86ce-262472d62f82.png)

**Comment by Aymkdn** [comment]
The `white-space` property is not a supported style. I'll see if I can add it.

**Comment by Aymkdn** [comment]
I added the support in v2.1.6 – it's based on the `preserveLeadingSpaces` property of PDFMake.
