### ISSUE TITLE
Is it possible to hide certain elements?

### ISSUE THREAD

**Issue by lartheon** [Aymkdn/html-to-pdfmake#98]
Thank you for making this package, it's been a life saver! 
My html has a few elements such as icons, footer rows on tables etc. these aren't rendered very nicely when producing a pdf, Is it possible to hide these when creating a pdf for print?

Many thanks

**Comment by Aymkdn** [comment]
You should not include the HTML code that you don't want to convert to PDFMake. There is no other method to ignore some HTML code.

If you have a suggestion, I'm opened to suggestions.

**Comment by lartheon** [comment]
> You should not include the HTML code that you don't want to convert to PDFMake. There is no other method to ignore some HTML code.
> 
> If you have a suggestion, I'm opened to suggestions.

Thanks for replying, I ended up just using a while loop that looks for specific classes and removes the element.
I'll leave the code here if anyone stumbles across this thread.

```
removeElementByClassName(className: string): void {
      var elements = document?.getElementsByClassName(className);
      if(elements != null){
        while(elements.length > 0){
          elements[0].parentNode?.removeChild(elements[0]);
        }
      }
    }
```
